// BznsBrain's words, English and Arabic side by side so neither drifts. `{name}` is filled by t().
const T = {
  title: ['BznsBrain', 'BznsBrain'],
  testLayla: ['Test Layla', 'جرّب ليلى'],
  publish: ['Publish', 'انشر'],
  publishing: ['Publishing…', 'جارٍ النشر…'],
  published: ['Published.', 'تم النشر.'],
  nothingToPublish: ['Everything is published', 'كل شيء منشور'],
  statusLive: ['Live', 'منشور'],
  statusChanges: ['Changes not published', 'تعديلات غير منشورة'],
  statusNew: ['Not published yet', 'لم يُنشر بعد'],
  tabsLabel: ['Data entry', 'إدخال البيانات'],
  tabCatalog: ['Catalog', 'الكتالوج'],
  loading: ['Loading…', 'جارٍ التحميل…'],
  retry: ['Try again', 'حاول مجدداً'],
  saved: ['Saved', 'تم الحفظ'],
  // Steps
  stepsTitle: ['Finish setup', 'أكمل الإعداد'],
  stepsDone: ['{done} of {total} done', 'أُنجز {done} من {total}'],
  step_industry: ['Choose your industry', 'اختر مجالك'],
  step_information: ['Add your information', 'أضف معلوماتك'],
  step_review: ['Review suggestions', 'راجع الاقتراحات'],
  step_behaviour: ['Configure Layla', 'اضبط ليلى'],
  step_test: ['Run a test', 'أجرِ تجربة'],
  step_channel: ['Connect a channel', 'اربط قناة'],
  step_active: ['Turn Layla on', 'شغّل ليلى'],
  open: ['Open', 'افتح'],
  // bzns.md
  bznsStart: ['Start from the {industry} template', 'ابدأ من قالب {industry}'],
  bznsEmpty: ['bzns.md is empty.', 'ملف bzns.md فارغ.'],
  bznsField: ['bzns.md text', 'نص bzns.md'],
  saveDraft: ['Save draft', 'احفظ المسودة'],
  saving: ['Saving…', 'جارٍ الحفظ…'],
  draftSaved: ['Draft saved.', 'حُفظت المسودة.'],
  sections: ['Sections', 'الأقسام'],
  added: ['added', 'مضاف'],
  missing: ['missing', 'غير مضاف'],
  beforePublish: ['Before publishing:', 'قبل النشر:'],
  // Catalog
  catalogEmpty: ['No services or products yet.', 'لا توجد خدمات أو منتجات بعد.'],
  addItem: ['Add a service or product', 'أضف خدمة أو منتجاً'],
  editItem: ['Edit', 'تعديل'],
  archive: ['Remove', 'إزالة'],
  discard: ['Undo change', 'تراجع عن التعديل'],
  kind_service: ['Service', 'خدمة'],
  kind_product: ['Product', 'منتج'],
  state_published: ['Published', 'منشور'],
  state_draft: ['Draft', 'مسودة'],
  state_changed: ['Changed', 'معدَّل'],
  fromStock: ['From Stock', 'من المخزون'],
  nameEn: ['Name in English', 'الاسم بالإنجليزية'],
  nameAr: ['Name in Arabic', 'الاسم بالعربية'],
  kind: ['Type', 'النوع'],
  description: ['Description', 'الوصف'],
  priceType: ['Price', 'السعر'],
  price_fixed: ['Fixed price', 'سعر ثابت'],
  price_from: ['Starting from', 'ابتداءً من'],
  price_range: ['Range', 'نطاق'],
  price_free: ['Free', 'مجاني'],
  price_quote: ['Quote on request', 'حسب عرض السعر'],
  price_recurring: ['Per month', 'شهرياً'],
  price_none: ['No price', 'بدون سعر'],
  amount: ['Amount', 'المبلغ'],
  minimum: ['From', 'من'],
  maximum: ['To', 'إلى'],
  currency: ['Currency', 'العملة'],
  saveItem: ['Save', 'احفظ'],
  cancel: ['Cancel', 'إلغاء'],
  search: ['Search the catalog', 'ابحث في الكتالوج'],
  // Add information
  addTitle: ['Add from a file, website or text', 'أضف من ملف أو موقع أو نص'],
  addFile: ['Choose a file', 'اختر ملفاً'],
  website: ['Website address', 'عنوان الموقع'],
  readWebsite: ['Read website', 'اقرأ الموقع'],
  paste: ['Paste text', 'الصق نصاً'],
  readText: ['Read text', 'اقرأ النص'],
  reading: ['Reading part {done} of {total}…', 'جارٍ قراءة الجزء {done} من {total}…'],
  readDone: ['{added} suggestions to review.', '{added} اقتراحات للمراجعة.'],
  readNothingNew: ['Nothing new: it is already in BznsBrain.', 'لا جديد: موجود بالفعل في BznsBrain.'],
  readNothing: ['Nothing found to add.', 'لم يُعثر على ما يُضاف.'],
  add_file: ['File', 'ملف'],
  add_website: ['Website', 'موقع'],
  add_text: ['Text', 'نص'],
  optional: ['optional', 'اختياري'],
  websiteOff: ['Website reading is not available yet.', 'قراءة المواقع غير متاحة بعد.'],
  readPartial: ['Only the first part was read; the rest was too long.', 'قُرئ الجزء الأول فقط؛ الباقي طويل جداً.'],
  readFailed: ['Layla could not read part of it. Try again in a moment.', 'تعذّر على ليلى قراءة جزء منه. حاول بعد قليل.'],
  // Review
  reviewTitle: ['Needs your review', 'بحاجة لمراجعتك'],
  reviewNone: ['Nothing to review.', 'لا شيء للمراجعة.'],
  reviewCount: ['{count} to review', '{count} للمراجعة'],
  showAll: ['Show all', 'اعرض الكل'],
  showLess: ['Show fewer', 'اعرض أقل'],
  kind_bzns_section: ['For bzns.md', 'لملف bzns.md'],
  kind_catalog_entry: ['For the Catalog', 'للكتالوج'],
  kind_qa_migration: ['Old answer to move into bzns.md', 'إجابة قديمة لنقلها إلى bzns.md'],
  kind_customer_gap: ['Customers asked, not covered', 'سأل العملاء ولا توجد إجابة'],
  askedTimes: ['Asked {count} times', 'سُئل {count} مرات'],
  current: ['Now', 'الحالي'],
  proposed: ['Suggested', 'المقترح'],
  nothingYet: ['Nothing yet', 'لا شيء بعد'],
  source: ['Source', 'المصدر'],
  accept: ['Accept', 'اقبل'],
  edit: ['Edit', 'عدّل'],
  dismiss: ['Dismiss', 'تجاهل'],
  answer: ['Your answer', 'إجابتك'],
  addAnswer: ['Add answer', 'أضف الإجابة'],
  section: ['Goes under', 'تحت قسم'],
  quarantined: ['This text reads like an instruction. Rewrite it in your own words to accept it.', 'هذا النص يشبه تعليمات. أعد كتابته بكلماتك لقبوله.'],
  acceptedNote: ['Added to draft.', 'أُضيف إلى المسودة.'],
  // Behaviour
  behaviourTitle: ['Layla\'s behaviour', 'طريقة تعامل ليلى'],
  tone: ['Style', 'الأسلوب'],
  askName: ['Ask the customer\'s name', 'اسأل عن اسم العميل'],
  askDetails: ['Layla asks for', 'تسأل ليلى عن'],
  appointmentPreferences: ['Preferred appointment time', 'الوقت المفضل للموعد'],
  handoffNote: ['When to give your team\'s contact', 'متى تعطي رقم فريقك'],
  industry: ['Industry', 'المجال'],
  saveBehaviour: ['Save behaviour', 'احفظ الإعدادات'],
  behaviourSaved: ['Saved.', 'تم الحفظ.'],
  // Test panel
  testTitle: ['Test Layla', 'جرّب ليلى'],
  testNote: ['Test only. Nothing is sent.', 'تجربة فقط. لا يُرسل شيء.'],
  testPublished: ['Published', 'المنشور'],
  testDraft: ['Draft', 'المسودة'],
  testingPublished: ['Testing what customers get now', 'تجربة ما يصل للعملاء الآن'],
  testingDraft: ['Testing your unpublished draft', 'تجربة مسودتك غير المنشورة'],
  testPlaceholder: ['Write as a customer…', 'اكتب كأنك عميل…'],
  send: ['Send', 'أرسل'],
  thinking: ['Layla is writing…', 'ليلى تكتب…'],
  reset: ['Start over', 'ابدأ من جديد'],
  close: ['Close', 'إغلاق'],
  sources: ['Sources', 'المصادر'],
  noSources: ['No business data used', 'لم تُستخدم بيانات النشاط'],
  captured: ['Captured', 'ما تم تسجيله'],
  why: ['Why', 'السبب'],
  gaveContact: ['Gave your team\'s contact', 'أعطت رقم فريقك'],
  fallback: ['Safe fallback used', 'استُخدم الرد الاحتياطي'],
  appointment: ['Appointment request for reception', 'طلب موعد للاستقبال'],
  noReply: ['No reply needed', 'لا يحتاج رداً'],
  // Errors
  err_generic: ['That did not work. Your saved data is safe. Try again.', 'لم ينجح ذلك. بياناتك المحفوظة آمنة. حاول مجدداً.'],
  err_manager_required: ['Only the business manager can change this.', 'يمكن لمدير النشاط فقط تغيير هذا.'],
  err_bzns_conflict: ['bzns.md changed in another tab. Reload before saving.', 'تغيّر bzns.md في نافذة أخرى. أعد التحميل قبل الحفظ.'],
  err_behaviour_conflict: ['These settings changed in another tab. Reload before saving.', 'تغيّرت هذه الإعدادات في نافذة أخرى. أعد التحميل قبل الحفظ.'],
  err_price_in_section: ['Prices belong in the Catalog, not bzns.md.', 'الأسعار مكانها الكتالوج وليس bzns.md.'],
  err_handoff_note_money: ['Prices belong in the Catalog, not here.', 'الأسعار مكانها الكتالوج وليس هنا.'],
  err_instruction_like: ['That reads like an instruction to an assistant. Write the fact itself.', 'هذا يشبه تعليمات لمساعد. اكتب المعلومة نفسها.'],
  err_answer_required: ['Write the answer first.', 'اكتب الإجابة أولاً.'],
  err_too_many: ['Layla has read a lot in the last hour. Try again later.', 'قرأت ليلى الكثير في الساعة الماضية. حاول لاحقاً.'],
  err_invalid_catalog_entry: ['Check the name and price, then save again.', 'تحقق من الاسم والسعر ثم احفظ مجدداً.'],
  err_catalog_limit: ['The catalog holds up to 1,000 items.', 'يتسع الكتالوج لألف عنصر كحد أقصى.'],
  err_bzns_too_long: ['bzns.md is too long. Shorten it before adding more.', 'ملف bzns.md طويل جداً. اختصره قبل الإضافة.'],
  err_website_url_invalid: ['That website address does not work. Check it and try again.', 'عنوان الموقع غير صالح. تحقق منه وحاول مجدداً.'],
};

/** @param {'en'|'ar'} lang */
export function brainStrings(lang = 'en') {
  const i = lang === 'ar' ? 1 : 0;
  const t = (key, vars = {}) => String(T[key]?.[i] ?? key).replace(/\{(\w+)\}/g, (_, k) => (vars[k] ?? `{${k}}`));
  const reason = code => (T[`err_${code}`] ? t(`err_${code}`) : t('err_generic'));
  return { lang, ar: lang === 'ar', t, reason };
}
export const BRAIN_STRING_KEYS = Object.freeze(Object.keys(T));
export const brainStringPairs = () => Object.entries(T);
