import { cronJobs } from 'convex/server';
import { internal } from './_generated/api';
const crons = cronJobs();
crons.interval('recover Blue message jobs', {minutes:1}, internal.blueMessaging.maintain);
crons.interval('start and recover Blue campaigns', {minutes:1}, internal.blueCampaign.maintain);
crons.interval('expire Blue review records', { minutes: 15 }, internal.review.cleanup);
crons.interval('expire blue auth codes', {minutes: 15}, internal.blueAuth.cleanup);
crons.interval('maintain Instagram connections', {minutes:15}, internal.blueInstagram.maintain);
crons.interval('remove unused Hasib photo uploads', {hours:1}, internal.blueHasib.sweepPhotos);
export default crons;
