import React, { useCallback, useEffect, useState } from 'react';
import { hasib } from '../../lib/dashboard/api';
import { ActionCards, EmptyState, MetricCards, PageHeader } from './DashboardVisuals';

const money=(minor,ar)=>`${new Intl.NumberFormat(ar?'ar-OM':'en-OM',{minimumFractionDigits:3,maximumFractionDigits:3}).format((minor||0)/1000)} ${ar?'ر.ع.':'OMR'}`;
const percent=(value,ar)=>value==null?(ar?'بيانات غير كافية':'Not enough records'):new Intl.NumberFormat(ar?'ar-OM':'en-OM',{style:'percent',maximumFractionDigits:1}).format(value);
const ratio=(value,ar)=>value==null?(ar?'بيانات غير كافية':'Not enough records'):new Intl.NumberFormat(ar?'ar-OM':'en-OM',{maximumFractionDigits:2}).format(value);
const date=value=>new Date(value).toISOString().slice(0,10);
const nextStatus={tender:'quoted',quoted:'awarded',awarded:'active',active:'practical_completion',practical_completion:'defects_liability',defects_liability:'closed'};
const RECORD_ACTIONS=['milestone','progress','cost','variation','claim'];
const SITE_ACTIONS=['commitment','report','quality','risk'];

export function ConstructionDashboard({mode,s,overview,onChanged,onGo,initialAction=''}){
  const ar=s.ar,tr=(en,arabic)=>ar?arabic:en;
  const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[showProject,setShowProject]=useState(initialAction==='project'),[recordType,setRecordType]=useState(RECORD_ACTIONS.includes(initialAction)?initialAction:''),[siteAction,setSiteAction]=useState(SITE_ACTIONS.includes(initialAction)?initialAction:''),[showInvite,setShowInvite]=useState(initialAction==='invite');
  useEffect(()=>{setShowProject(initialAction==='project');setRecordType(RECORD_ACTIONS.includes(initialAction)?initialAction:'');setSiteAction(SITE_ACTIONS.includes(initialAction)?initialAction:'');setShowInvite(initialAction==='invite');},[initialAction]);
  const load=useCallback(async()=>{setError('');try{
    if(mode==='money')setData(await hasib('construction_insights'));
    else if(mode==='team')setData(await hasib('team_list'));
    else if(mode==='procurement'){const [overviewData,commitments,quality,risks,reports]=await Promise.all([hasib('construction_overview'),...['construction_commitments','construction_quality','construction_risks','construction_site_reports'].map(operation=>hasib(operation))]);setData({projects:overviewData.projects,commitments:commitments.items,quality:quality.items,risks:risks.items,reports:reports.items});}
    else if(mode==='projects'){const [summary,milestones,progress,costs,variations,claims]=await Promise.all(['construction_overview','construction_milestones','construction_progress','construction_costs','construction_variations','construction_claims'].map(operation=>hasib(operation)));setData({...summary,milestones:milestones.items,progress:progress.items,costs:costs.items,variations:variations.items,claims:claims.items});}
    else setData(await hasib('construction_overview'));
  }catch(e){setError(e.reason||'construction_unavailable');}},[mode]);
  useEffect(()=>{load();},[load]);
  const mutate=async(operation,body)=>{setBusy(true);setError('');try{const result=await hasib(operation,{requestId:crypto.randomUUID(),...body});await load();onChanged?.();return result;}catch(e){setError(e.reason||'construction_update_failed');return null;}finally{setBusy(false);}};
  const createProject=async e=>{e.preventDefault();const element=e.currentTarget,form=new FormData(element),start=new Date(form.get('start')).getTime(),finish=new Date(form.get('finish')).getTime();const result=await mutate('construction_project_save',{workflow:{reference:form.get('reference'),title:form.get('title'),location:form.get('location'),contractType:form.get('contractType'),originalContractMinor:Math.round(Number(form.get('contract'))*1000),originalBudgetMinor:Math.round(Number(form.get('budget'))*1000),estimateToCompleteMinor:Math.round(Number(form.get('budget'))*1000),startAt:start,contractFinishAt:finish,forecastFinishAt:finish}});if(result){element.reset();setShowProject(false);}};
  if(error)return <div className="ld-state" role="alert"><p>{error}</p><button className="ld-button" onClick={load}>{tr('Retry','إعادة المحاولة')}</button></div>;
  if(!data)return <p className="ld-state" role="status">{tr('Loading construction operations…','جارٍ تحميل عمليات المقاولات…')}</p>;

  if(mode==='today')return <div className="hb-construction"><PageHeader title={tr('Today','اليوم')} description={tr('The three exceptions that need management attention now.','الاستثناءات الثلاثة التي تحتاج انتباه الإدارة الآن.')} icon="building-2"/>
    <ActionCards label={tr('Quick actions','إجراءات سريعة')} actions={[{id:'project',label:tr('New project','مشروع جديد'),icon:'building-2',onClick:()=>onGo('orders',{action:'project'})},{id:'progress',label:tr('Record progress','تسجيل التقدم'),icon:'bar-chart',onClick:()=>onGo('orders',{action:'progress'})},{id:'variation',label:tr('Draft variation','مسودة تغيير'),icon:'receipt',onClick:()=>onGo('orders',{action:'variation'})},{id:'commitment',label:tr('Add commitment','إضافة التزام'),icon:'box',onClick:()=>onGo('stock',{action:'commitment'})}]} />
    <MetricCards label={tr('Today measures','مؤشرات اليوم')} items={[
      {id:'schedule-risk',value:data.metrics?.[0]?.value||0,label:tr('Projects at schedule risk','مشاريع معرضة للتأخير'),tone:'coral',onClick:()=>onGo('orders')},
      {id:'variations',value:money(data.metrics?.[1]?.value,ar),label:tr('Submitted variation exposure','قيمة التغييرات المقدمة'),onClick:()=>onGo('orders')},
      {id:'receivables',value:money(data.metrics?.[2]?.value,ar),label:tr('Overdue certified receivables','مستحقات معتمدة متأخرة'),onClick:overview.capabilities?.money===false?undefined:()=>onGo('money')},
    ]}/>
    <section className="hb-real-grid"><section className="hb-panel"><h2>{tr('Active projects','المشاريع النشطة')}</h2>{data.projects?.length?<ProjectList rows={data.projects.slice(0,8)} tr={tr}/>:<EmptyState icon="building-2" title={tr('No projects yet','لا توجد مشاريع بعد')} description={tr('Create a tender or awarded job from Projects.','أنشئ مناقصة أو عملاً مسنداً من المشاريع.')}/>}</section><section className="hb-panel"><h2>{tr('Operational tasks','المهام التشغيلية')}</h2>{data.tasks?.length?<ul className="hb-clinic-list">{data.tasks.map(row=><li key={row.id}><span>{row.reason}</span><button className="ld-button" disabled={busy} onClick={()=>mutate('construction_task_resolve',{taskId:row.id})}>{tr('Resolve','إغلاق')}</button></li>)}</ul>:<p>{tr('Nothing needs attention.','لا توجد مهام تحتاج متابعة.')}</p>}</section></section>
  </div>;

  if(mode==='projects')return <div className="hb-construction"><PageHeader title={tr('Projects','المشاريع')} description={tr('Tender, baseline, progress, variations, claims and close-out in one controlled lifecycle.','المناقصة وخط الأساس والتقدم والتغييرات والمطالبات والإغلاق ضمن دورة مضبوطة.')} icon="building-2"/>
    <ActionCards label={tr('Project actions','إجراءات المشروع')} actions={[{id:'project',label:tr('New project','مشروع جديد'),icon:'building-2',onClick:()=>setShowProject(x=>!x)},{id:'milestone',label:tr('Add baseline milestone','إضافة مرحلة لخط الأساس'),icon:'calendar',onClick:()=>setRecordType('milestone')},{id:'progress',label:tr('Record progress','تسجيل التقدم'),icon:'bar-chart',onClick:()=>setRecordType('progress')},{id:'cost',label:tr('Record project cost','تسجيل تكلفة المشروع'),icon:'receipt',onClick:()=>setRecordType('cost')},{id:'variation',label:tr('Draft variation','مسودة تغيير'),icon:'repeat',onClick:()=>setRecordType('variation')},{id:'claim',label:tr('Draft claim','مسودة مطالبة'),icon:'receipt',onClick:()=>setRecordType('claim')}]} />
    {showProject&&<form className="hb-panel hb-construction-form" onSubmit={createProject}><h2>{tr('Project controls','بيانات المشروع')}</h2><label>{tr('Reference','المرجع')}<input name="reference" maxLength="40" required/></label><label>{tr('Project name','اسم المشروع')}<input name="title" maxLength="120" required/></label><label>{tr('Location','الموقع')}<input name="location" maxLength="160" required/></label><label>{tr('Contract type','نوع العقد')}<select name="contractType"><option value="lump_sum">{tr('Lump sum','مبلغ مقطوع')}</option><option value="remeasurement">{tr('Remeasurement','إعادة قياس')}</option><option value="design_build">{tr('Design-build','تصميم وتنفيذ')}</option><option value="cost_plus">{tr('Cost plus','تكلفة مضافة')}</option></select></label><label>{tr('Contract value (OMR)','قيمة العقد (ر.ع.)')}<input name="contract" type="number" min="0" step="0.001" required/></label><label>{tr('Cost baseline (OMR)','خط أساس التكلفة (ر.ع.)')}<input name="budget" type="number" min="0" step="0.001" required/></label><label>{tr('Start date','تاريخ البدء')}<input name="start" type="date" required/></label><label>{tr('Contract finish','نهاية العقد')}<input name="finish" type="date" required/></label><button className="ld-button primary" disabled={busy}>{tr('Create project','إنشاء المشروع')}</button></form>}
    {recordType&&<ConstructionRecordForm type={recordType} projects={data.projects||[]} milestones={data.milestones||[]} tr={tr} busy={busy} onClose={()=>setRecordType('')} onSave={async(operation,body)=>{const result=await mutate(operation,body);if(result)setRecordType('');}}/>}
    {data.projects?.length?<div className="hb-construction-projects">{data.projects.map(row=><article className="hb-panel" key={row.id}><div className="hb-construction-heading"><div><h2>{row.title}</h2><p>{row.reference} · {row.location}</p></div><span className="ld-chip">{row.status}</span></div><dl className="hb-clinic-governance"><div><dt>{tr('Contract','العقد')}</dt><dd>{money(row.originalContractMinor,ar)}</dd></div><div><dt>{tr('Budget','الميزانية')}</dt><dd>{money(row.originalBudgetMinor,ar)}</dd></div><div><dt>{tr('Forecast finish','النهاية المتوقعة')}</dt><dd>{date(row.forecastFinishAt)}</dd></div></dl><div className="ld-actions">{nextStatus[row.status]&&<button className="ld-button" disabled={busy} onClick={()=>mutate('construction_project_status',{projectId:row.id,version:row.version,status:nextStatus[row.status]})}>{tr(`Move to ${nextStatus[row.status].replaceAll('_',' ')}`,`نقل إلى ${nextStatus[row.status]}`)}</button>}{!row.baselineApprovedAt&&overview.workspaceRole==='manager'&&<button className="ld-button" disabled={busy} onClick={()=>mutate('construction_baseline_approve',{projectId:row.id,version:row.version})}>{tr('Approve baseline','اعتماد خط الأساس')}</button>}</div></article>)}</div>:<EmptyState icon="building-2" title={tr('No projects yet','لا توجد مشاريع بعد')} description={tr('Start with a project, then add weighted milestones whose total is 100%.','ابدأ بمشروع ثم أضف مراحل موزونة مجموعها ١٠٠٪.')}/>}
    {data.projects?.length>0&&<div className="hb-real-grid"><SimplePanel title={tr('Baseline milestones','مراحل خط الأساس')} rows={data.milestones} tr={tr}/><SimplePanel title={tr('Progress records','سجلات التقدم')} rows={data.progress} tr={tr}/><SimplePanel title={tr('Project costs','تكاليف المشروع')} rows={data.costs} tr={tr}/><SimplePanel title={tr('Variations','التغييرات')} rows={data.variations} tr={tr} action={row=>{const status=row.status==='draft'?'submitted':row.status==='submitted'&&overview.workspaceRole==='manager'?'approved':null;return status?{label:tr(status==='submitted'?'Submit variation':'Approve variation',status==='submitted'?'تقديم التغيير':'اعتماد التغيير'),run:()=>mutate('construction_variation_status',{variationId:row.id,version:row.version,status})}:null;}}/><SimplePanel title={tr('Payment claims','مطالبات الدفع')} rows={data.claims} tr={tr} action={row=>{const status=row.status==='draft'?'submitted':row.status==='submitted'&&overview.workspaceRole==='manager'?'certified':null;return status?{label:tr(status==='submitted'?'Submit claim':'Certify claim',status==='submitted'?'تقديم المطالبة':'اعتماد المطالبة'),run:()=>mutate('construction_claim_status',{claimId:row.id,version:row.version,status})}:null;}}/></div>}</div>;

  if(mode==='procurement')return <div className="hb-construction"><PageHeader title={tr('Procurement & site controls','المشتريات وضبط الموقع')} description={tr('Commitments, delivery performance, site reports, quality findings and risks.','الالتزامات وأداء التسليم وتقارير الموقع وملاحظات الجودة والمخاطر.')} icon="box"/>
    <ActionCards label={tr('Site actions','إجراءات الموقع')} actions={[{id:'commitment',label:tr('Add commitment','إضافة التزام'),icon:'box',onClick:()=>setSiteAction('commitment')},{id:'report',label:tr('Daily site report','تقرير الموقع اليومي'),icon:'calendar',onClick:()=>setSiteAction('report')},{id:'quality',label:tr('Quality / NCR','الجودة / عدم المطابقة'),icon:'shield',onClick:()=>setSiteAction('quality')},{id:'risk',label:tr('Add risk','إضافة خطر'),icon:'alert-triangle',onClick:()=>setSiteAction('risk')}]} />
    {siteAction&&<ConstructionSiteForm type={siteAction} projects={data.projects||[]} tr={tr} busy={busy} onClose={()=>setSiteAction('')} onSave={async(operation,body)=>{const result=await mutate(operation,body);if(result)setSiteAction('');}}/>}
    <div className="hb-real-grid"><SimplePanel title={tr('Commitments','الالتزامات')} rows={data.commitments} tr={tr} action={row=>{const status={draft:'approved',approved:'ordered',ordered:'delivered',delivered:'closed'}[row.status];return status&&(row.status!=='draft'||overview.workspaceRole==='manager')?{label:tr(`Move to ${status}`,`نقل إلى ${status}`),run:()=>mutate('construction_commitment_status',{commitmentId:row.id,version:row.version,status})}:null;}}/><SimplePanel title={tr('Quality / NCR','الجودة / عدم المطابقة')} rows={data.quality} tr={tr} action={row=>row.status!=='closed'?{label:tr(row.status==='open'?'Start corrective action':'Close finding',row.status==='open'?'بدء الإجراء التصحيحي':'إغلاق الملاحظة'),run:()=>mutate('construction_quality_status',{qualityId:row.id,version:row.version,status:row.status==='open'?'mitigating':'closed'})}:null}/><SimplePanel title={tr('Project risks','مخاطر المشروع')} rows={data.risks} tr={tr} action={row=>row.status!=='closed'?{label:tr(row.status==='open'?'Start mitigation':'Close risk',row.status==='open'?'بدء المعالجة':'إغلاق الخطر'),run:()=>mutate('construction_risk_status',{riskId:row.id,version:row.version,status:row.status==='open'?'mitigating':'closed'})}:null}/><SimplePanel title={tr('Site reports','تقارير الموقع')} rows={data.reports} tr={tr}/></div></div>;

  if(mode==='money'){const m=data.metrics||{},c=data.coverage||{};return <div className="hb-construction"><PageHeader title={tr('Money & insights','الأموال والمؤشرات')} description={tr('Contract, earned-value, delivery, quality, safety and cash measures with visible coverage. Targets remain unset until a 30-day baseline exists.','مؤشرات العقد والقيمة المكتسبة والتسليم والجودة والسلامة والنقد مع تغطية واضحة. تبقى الأهداف غير محددة حتى توفر خط أساس لمدة ٣٠ يوماً.')} icon="bar-chart"/><MetricCards label={tr('Project performance','أداء المشاريع')} items={[
    {id:'contract',value:money(m.revisedContractMinor,ar),label:tr('Revised contract value','قيمة العقد المعدلة')},{id:'forecast',value:money(m.forecastFinalCostMinor,ar),label:tr('Forecast final cost','التكلفة النهائية المتوقعة')},{id:'margin',value:percent(m.forecastMargin,ar),label:tr('Forecast margin','الهامش المتوقع')},{id:'cpi',value:ratio(m.cpi,ar),label:tr('Cost performance index (CPI)','مؤشر أداء التكلفة')},{id:'spi',value:ratio(m.spi,ar),label:tr('Schedule performance index (SPI)','مؤشر أداء الجدول')},{id:'collection',value:percent(m.collectionRate,ar),label:tr('Collection rate','معدل التحصيل')},{id:'rework',value:percent(m.reworkRate,ar),label:tr('Rework cost rate','معدل تكلفة إعادة العمل')},{id:'safety',value:ratio(m.incidentFrequency,ar),label:tr('Recordables per 200k hours','الحوادث لكل ٢٠٠ ألف ساعة')},{id:'rating',value:ratio(m.clientRating,ar),label:tr('Client rating / 5','تقييم العميل / ٥')},
  ]}/><p className="ld-help">{tr(`Earned-value coverage: ${c.earnedValue?.numerator||0}/${c.earnedValue?.denominator||0} milestones. Safety reports: ${c.safety?.numerator||0}/${c.safety?.denominator||0} active projects.`,`تغطية القيمة المكتسبة: ${c.earnedValue?.numerator||0}/${c.earnedValue?.denominator||0} مرحلة. تقارير السلامة: ${c.safety?.numerator||0}/${c.safety?.denominator||0} مشروع نشط.`)}</p></div>}

  if(mode==='team')return <div className="hb-construction"><PageHeader title={tr('Team','الفريق')} description={tr(`One manager and up to ${data.limit||5} verified-email operations employees.`,`مدير واحد وحتى ${data.limit||5} موظفي عمليات ببريد موثّق.`)} icon="users" primary={{label:tr('Invite employee','دعوة موظف'),onClick:()=>setShowInvite(true)}}/>
    {showInvite&&<form className="hb-panel hb-construction-form" onSubmit={async e=>{e.preventDefault();const element=e.currentTarget,result=await mutate('team_invite',{email:new FormData(element).get('email')});if(result){element.reset();setShowInvite(false);}}}><h2>{tr('Invite operations employee','دعوة موظف عمليات')}</h2><label>{tr('Employee email','بريد الموظف')}<input name="email" type="email" maxLength="254" required/></label><div className="ld-actions"><button className="ld-button primary" disabled={busy}>{tr('Send invitation','إرسال الدعوة')}</button><button type="button" className="ld-button" onClick={()=>setShowInvite(false)}>{tr('Cancel','إلغاء')}</button></div></form>}
    {data.members?.length?<ul className="hb-clinic-list">{data.members.map(row=><li key={row.id}><span>{row.email}</span><span className="ld-chip">{row.status}</span>{row.status==='pending'&&<button className="ld-button" disabled={busy} onClick={()=>mutate('team_resend',{memberId:row.id})}>{tr('Resend','إعادة الإرسال')}</button>}{row.status!=='revoked'&&<button className="ld-button ld-danger" disabled={busy} onClick={()=>mutate('team_revoke',{memberId:row.id})}>{tr('Revoke','إلغاء الصلاحية')}</button>}</li>)}</ul>:<EmptyState icon="users" title={tr('No employees yet','لا يوجد موظفون بعد')} description={tr('Invite operations staff when you are ready.','ادعُ موظفي العمليات عندما تكون جاهزاً.')} action={{label:tr('Invite employee','دعوة موظف'),onClick:()=>setShowInvite(true)}}/>}</div>;

  return <div className="hb-construction"><PageHeader title={tr('Construction settings','إعدادات المقاولات')} description={tr('Operational defaults, access boundaries and KPI definitions.','الإعدادات التشغيلية وحدود الوصول وتعريفات المؤشرات.')} icon="shield"/><section className="hb-panel"><h2>{tr('Release defaults','إعدادات الإصدار')}</h2><dl className="hb-clinic-governance"><div><dt>{tr('Timezone','المنطقة الزمنية')}</dt><dd>Asia/Muscat</dd></div><div><dt>{tr('Performance targets','أهداف الأداء')}</dt><dd>{tr('Unset until 30-day baseline','غير محددة حتى خط أساس ٣٠ يوماً')}</dd></div><div><dt>{tr('Employee access','صلاحية الموظف')}</dt><dd>{tr('Operations and drafts only','العمليات والمسودات فقط')}</dd></div></dl><form className="hb-construction-form" onSubmit={e=>{e.preventDefault();const value=Number(new FormData(e.currentTarget).get('denominator'));mutate('settings_update',{constructionIncidentHoursDenominator:value});}}><label>{tr('Safety frequency denominator (worker hours)','مقام معدل السلامة (ساعات العمل)')}<input name="denominator" type="number" min="10000" max="1000000" step="10000" defaultValue={overview.settings?.constructionIncidentHoursDenominator||200000} required/></label><button className="ld-button" disabled={busy}>{tr('Save safety denominator','حفظ مقام السلامة')}</button></form><p className="ld-help">{tr('Managers control baselines, approvals, certified claims, retention, aggregate money, exports, team and settings.','يتحكم المديرون في خطوط الأساس والموافقات والمطالبات المعتمدة والاحتجاز والأموال المجمعة والتصدير والفريق والإعدادات.')}</p></section></div>;
}

function ProjectList({rows,tr}){return <ul className="hb-clinic-list">{rows.map(row=><li key={row.id}><span>{row.title}</span><span className="ld-chip">{tr(row.status,row.status)}</span></li>)}</ul>}
function SimplePanel({title,rows=[],tr,action}){return <section className="hb-panel"><h2>{title}</h2>{rows.length?<ul className="hb-clinic-list">{rows.slice(0,20).map(row=>{const next=action?.(row),label=row.supplier||row.label||row.title||row.reference||row.category||(row.asOfAt?`${tr('Progress','التقدم')} · ${date(row.asOfAt)}`:row.reportDate?date(row.reportDate):tr('Recorded item','سجل'));return <li key={row.id}><span>{label}</span><span className="ld-chip">{row.status||tr('recorded','مسجل')}</span>{next&&<button type="button" className="ld-button" onClick={next.run}>{next.label}</button>}</li>})}</ul>:<p>{tr('No records yet.','لا توجد سجلات بعد.')}</p>}</section>}

function ConstructionSiteForm({type,projects,tr,busy,onClose,onSave}){
  const submit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),projectId=f.get('projectId'),stamp=name=>new Date(f.get(name)).getTime(),number=name=>Number(f.get(name)||0),minor=name=>Math.round(number(name)*1000);let operation,workflow={projectId};
    if(type==='commitment'){operation='construction_commitment_save';workflow={...workflow,kind:f.get('kind'),supplier:f.get('supplier'),package:f.get('package'),label:f.get('label'),amountMinor:minor('amount'),requiredAt:stamp('required')};}
    if(type==='report'){operation='construction_site_report_save';workflow={...workflow,reportDate:stamp('date'),workerHours:number('hours'),toolboxTalks:number('toolbox'),inspections:number('inspections'),recordableIncidents:number('recordables'),lostTimeIncidents:number('lostTime'),lostDays:number('lostDays')};}
    if(type==='quality'){operation='construction_quality_save';workflow={...workflow,kind:f.get('kind'),severity:f.get('severity'),title:f.get('title'),dueAt:stamp('due')};}
    if(type==='risk'){operation='construction_risk_save';workflow={...workflow,category:f.get('category'),title:f.get('title'),probability:number('probability'),impact:number('impact'),mitigation:f.get('mitigation'),dueAt:stamp('due')};}
    onSave(operation,{projectId,workflow});
  };
  const titles={commitment:tr('Procurement commitment','التزام المشتريات'),report:tr('Daily site report','تقرير الموقع اليومي'),quality:tr('Quality finding / NCR','ملاحظة جودة / عدم مطابقة'),risk:tr('Project risk','خطر المشروع')};
  return <form className="hb-panel hb-construction-form" onSubmit={submit}><h2>{titles[type]}</h2><label>{tr('Project','المشروع')}<select name="projectId" required><option value="">—</option>{projects.map(p=><option key={p.id} value={p.id}>{p.reference} · {p.title}</option>)}</select></label>
    {type==='commitment'&&<><label>{tr('Type','النوع')}<select name="kind"><option value="purchase_order">{tr('Purchase order','أمر شراء')}</option><option value="subcontract">{tr('Subcontract','مقاولة باطن')}</option><option value="rental">{tr('Equipment rental','تأجير معدات')}</option></select></label><label>{tr('Supplier','المورد')}<input name="supplier" maxLength="120" required/></label><label>{tr('Package','الحزمة')}<input name="package" maxLength="100" required/></label><label>{tr('Description','الوصف')}<input name="label" maxLength="120" required/></label><label>{tr('Amount (OMR)','المبلغ (ر.ع.)')}<input name="amount" type="number" min="0.001" step="0.001" required/></label><label>{tr('Required date','تاريخ الطلب')}<input name="required" type="date" required/></label></>}
    {type==='report'&&<><label>{tr('Report date','تاريخ التقرير')}<input name="date" type="date" required/></label><label>{tr('Worker hours','ساعات العمل')}<input name="hours" type="number" min="0" step="1" required/></label><label>{tr('Toolbox talks','اجتماعات السلامة')}<input name="toolbox" type="number" min="0" step="1" required/></label><label>{tr('Inspections','عمليات التفتيش')}<input name="inspections" type="number" min="0" step="1" required/></label><label>{tr('Recordable incidents','الحوادث المسجلة')}<input name="recordables" type="number" min="0" step="1" required/></label><label>{tr('Lost-time incidents','حوادث الوقت الضائع')}<input name="lostTime" type="number" min="0" step="1" required/></label><label>{tr('Lost days','أيام العمل الضائعة')}<input name="lostDays" type="number" min="0" step="1" required/></label></>}
    {type==='quality'&&<><label>{tr('Finding type','نوع الملاحظة')}<select name="kind"><option value="ncr">NCR</option><option value="inspection">{tr('Inspection finding','ملاحظة تفتيش')}</option><option value="snag">{tr('Snag','ملاحظة استلام')}</option></select></label><label>{tr('Severity','الخطورة')}<select name="severity">{['low','medium','high','critical'].map(value=><option key={value} value={value}>{value}</option>)}</select></label><label>{tr('Title','العنوان')}<input name="title" maxLength="160" required/></label><label>{tr('Due date','تاريخ الاستحقاق')}<input name="due" type="date" required/></label></>}
    {type==='risk'&&<><label>{tr('Category','الفئة')}<select name="category">{['delivery','commercial','design','supply','authority','safety','quality'].map(value=><option key={value} value={value}>{value}</option>)}</select></label><label>{tr('Title','العنوان')}<input name="title" maxLength="160" required/></label><label>{tr('Probability (1–5)','الاحتمال (١–٥)')}<input name="probability" type="number" min="1" max="5" step="1" required/></label><label>{tr('Impact (1–5)','الأثر (١–٥)')}<input name="impact" type="number" min="1" max="5" step="1" required/></label><label>{tr('Mitigation','المعالجة')}<input name="mitigation" maxLength="300"/></label><label>{tr('Due date','تاريخ الاستحقاق')}<input name="due" type="date" required/></label></>}
    <div className="ld-actions"><button className="ld-button primary" disabled={busy}>{type==='commitment'?tr('Save commitment','حفظ الالتزام'):tr('Save','حفظ')}</button><button type="button" className="ld-button" onClick={onClose}>{tr('Cancel','إلغاء')}</button></div></form>;
}

function ConstructionRecordForm({type,projects,milestones,tr,busy,onClose,onSave}){
  const submit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),projectId=f.get('projectId'),minor=name=>Math.round(Number(f.get(name)||0)*1000),stamp=name=>new Date(f.get(name)).getTime();let operation,workflow={projectId};
    if(type==='milestone'){operation='construction_milestone_save';workflow={...workflow,label:f.get('label'),weightBps:Math.round(Number(f.get('weight'))*100),budgetMinor:minor('amount'),plannedStartAt:stamp('start'),plannedFinishAt:stamp('finish')};}
    if(type==='progress'){operation='construction_progress_save';workflow={...workflow,...(f.get('milestoneId')?{milestoneId:f.get('milestoneId')}:{}),asOfAt:stamp('date'),plannedBps:Math.round(Number(f.get('planned'))*100),actualBps:Math.round(Number(f.get('actual'))*100),workerHours:Number(f.get('hours'))};}
    if(type==='cost'){operation='construction_cost_save';workflow={...workflow,category:f.get('category'),amountMinor:minor('amount'),incurredAt:stamp('date'),rework:f.get('category')==='rework'};}
    if(type==='variation'){operation='construction_variation_save';workflow={...workflow,reference:f.get('reference'),title:f.get('title'),reason:f.get('reason'),contractDeltaMinor:minor('contractDelta'),budgetDeltaMinor:minor('budgetDelta'),scheduleDeltaDays:Number(f.get('days'))};}
    if(type==='claim'){operation='construction_claim_save';workflow={...workflow,reference:f.get('reference'),grossMinor:minor('gross'),retentionMinor:minor('retention'),advanceRecoveryMinor:minor('advance'),dueAt:stamp('due'),retentionReleaseAt:stamp('retentionDate')};}
    onSave(operation,{projectId,workflow});
  };
  const title={milestone:tr('Baseline milestone','مرحلة خط الأساس'),progress:tr('Progress record','سجل التقدم'),cost:tr('Project cost','تكلفة المشروع'),variation:tr('Variation draft','مسودة تغيير'),claim:tr('Payment claim draft','مسودة مطالبة دفع')}[type];
  return <form className="hb-panel hb-construction-form" onSubmit={submit}><h2>{title}</h2><label>{tr('Project','المشروع')}<select name="projectId" required><option value="">—</option>{projects.map(p=><option key={p.id} value={p.id}>{p.reference} · {p.title}</option>)}</select></label>
    {type==='milestone'&&<><label>{tr('Milestone','المرحلة')}<input name="label" maxLength="100" required/></label><label>{tr('Weight (%)','الوزن (%)')}<input name="weight" type="number" min="0.01" max="100" step="0.01" required/></label><label>{tr('Budget (OMR)','الميزانية (ر.ع.)')}<input name="amount" type="number" min="0" step="0.001" required/></label><label>{tr('Planned start','البدء المخطط')}<input name="start" type="date" required/></label><label>{tr('Planned finish','النهاية المخططة')}<input name="finish" type="date" required/></label></>}
    {type==='progress'&&<><label>{tr('Milestone (optional)','المرحلة (اختياري)')}<select name="milestoneId"><option value="">—</option>{milestones.map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select></label><label>{tr('As of','حتى تاريخ')}<input name="date" type="date" required/></label><label>{tr('Planned progress (%)','التقدم المخطط (%)')}<input name="planned" type="number" min="0" max="100" step="0.01" required/></label><label>{tr('Accepted physical progress (%)','التقدم الفعلي المقبول (%)')}<input name="actual" type="number" min="0" max="100" step="0.01" required/></label><label>{tr('Worker hours','ساعات العمل')}<input name="hours" type="number" min="0" step="1" required/></label></>}
    {type==='cost'&&<><label>{tr('Cost category','فئة التكلفة')}<select name="category">{['labor','material','subcontract','equipment','overhead','rework','other'].map(x=><option key={x}>{x}</option>)}</select></label><label>{tr('Amount (OMR)','المبلغ (ر.ع.)')}<input name="amount" type="number" min="0.001" step="0.001" required/></label><label>{tr('Incurred date','تاريخ التكلفة')}<input name="date" type="date" required/></label></>}
    {type==='variation'&&<><label>{tr('Reference','المرجع')}<input name="reference" maxLength="40" required/></label><label>{tr('Title','العنوان')}<input name="title" maxLength="120" required/></label><label>{tr('Reason category','فئة السبب')}<select name="reason"><option value="client_instruction">client_instruction</option><option value="design_change">design_change</option><option value="site_condition">site_condition</option><option value="authority_requirement">authority_requirement</option></select></label><label>{tr('Contract change (OMR)','تغيير العقد (ر.ع.)')}<input name="contractDelta" type="number" step="0.001" required/></label><label>{tr('Budget effect (OMR)','أثر الميزانية (ر.ع.)')}<input name="budgetDelta" type="number" step="0.001" required/></label><label>{tr('Schedule change (days)','تغيير الجدول (أيام)')}<input name="days" type="number" step="1" required/></label></>}
    {type==='claim'&&<><label>{tr('Claim reference','مرجع المطالبة')}<input name="reference" maxLength="40" required/></label><label>{tr('Gross (OMR)','الإجمالي (ر.ع.)')}<input name="gross" type="number" min="0.001" step="0.001" required/></label><label>{tr('Retention (OMR)','الاحتجاز (ر.ع.)')}<input name="retention" type="number" min="0" step="0.001" required/></label><label>{tr('Advance recovery (OMR)','استرداد الدفعة المقدمة (ر.ع.)')}<input name="advance" type="number" min="0" step="0.001" required/></label><label>{tr('Payment due','استحقاق الدفع')}<input name="due" type="date" required/></label><label>{tr('Retention release date','تاريخ تحرير الاحتجاز')}<input name="retentionDate" type="date" required/></label></>}
    <div className="ld-actions"><button className="ld-button primary" disabled={busy}>{tr('Save','حفظ')}</button><button type="button" className="ld-button" onClick={onClose}>{tr('Cancel','إلغاء')}</button></div></form>;
}
