import test from 'node:test';
import assert from 'node:assert/strict';
import { answerMessage, buildContext, cacheKey, createDebouncer, reciprocalRankFusion, normalizeArabicLexical, chunkMarkdown, extractSlots, classifyKnn } from '../api/_lib/layla/rag-engine.js';

test('cache keys and tier zero are tenant and revision scoped', async()=>{const cache=new Map();const key=cacheKey({tenantId:'a',revision:1,query:'Hours?'});assert.notEqual(key,cacheKey({tenantId:'b',revision:1,query:'Hours?'}));const r=await answerMessage({tenantId:'a',revision:1,text:'What are your hours?',profile:{hours:'9–5'},cache:{get:k=>cache.get(k),set:(k,v)=>cache.set(k,v)}});assert.equal(r.tier,1);const hit=await answerMessage({tenantId:'a',revision:1,text:'What are your hours?',profile:{hours:'9–5'},cache:{get:k=>cache.get(k),set:(k,v)=>cache.set(k,v)}});assert.equal(hit.cache,'hit');});
test('RRF applies tenant filtering and low similarity falls back', async()=>{const r=await answerMessage({tenantId:'a',revision:1,text:'unusual policy',profile:{},lexicalSearch:async()=>[{id:'x',tenantId:'b',text:'secret'}],vectorSearch:async()=>[{id:'y',tenantId:'a',similarity:.5,text:'weak'}],generate:async()=>({text:'bad'})});assert.equal(r.fallback,'low_retrieval_confidence');const fused=reciprocalRankFusion([[{id:'a'}],[{id:'a'},{id:'b'}]]);assert.equal(fused[0].id,'a');});
test('context keeps six turns and records compaction',()=>{const r=buildContext(Array.from({length:10},(_,i)=>({role:i%2?'assistant':'user',text:String(i)})));assert.equal(r.turns.length,6);assert.equal(r.olderTurns,4);});
test('debouncer flushes one aggregate per conversation',async()=>{const flushed=[];const d=createDebouncer({delayMs:5,maxMs:30,onFlush:(key,messages)=>flushed.push([key,messages])});d.push('c',{id:1});d.push('c',{id:2});await new Promise(r=>setTimeout(r,15));assert.equal(flushed.length,1);assert.equal(flushed[0][1].length,2);});
test('Arabic lexical normalization preserves searchable equivalence',()=>assert.equal(normalizeArabicLexical('إِقامة ة ى'),'اقامه ه ي'));
test('heading chunking prepends context and bounds ordinary sections',()=>{const rows=chunkMarkdown('# Prices\n\nCleaning OMR 10\n\n# Hours\n\nOpen daily');assert.equal(rows.length,2);assert.match(rows[0].text,/^# Business facts > Prices/);});
test('closed vocabulary slots normalize digits and canonical IDs',()=>{const r=extractSlots('احجز تنظيف ١٢٣٤٥٦٧٨٩', {services:[{id:'cleaning',name:'تنظيف'}]});assert.equal(r.serviceId,'cleaning');assert.equal(r.phone,'123456789');});
test('kNN classifier returns a probability vector',()=>{const r=classifyKnn('book', [{intent:'book',text:'book',similarity:1},{intent:'price',text:'price',similarity:.2}]);assert.equal(r.intent,'book');assert.ok(r.probabilities.book>r.probabilities.price);});
