// Dashboard copy, Arabic and English. Plain, specific and short; reasons map
// server codes to what the owner can do next.
const en = {
  title: 'Layla dashboard', loadEarlier: 'Load earlier messages', nav: 'Dashboard sections', today: 'Today', money: 'Money', customers: 'Customers', settings: 'Settings', sectionViews: 'Views in this section',
  view_products: 'Products', view_services: 'Services', view_insights: 'Summary', view_expenses: 'Expenses', view_contacts: 'Customer list', view_broadcast: 'Message many', view_channels: 'Channels', view_business: 'Business details',
  broadcast: 'Broadcast', chats: 'Chats', contacts: 'Contacts', business: 'Business',
  active: 'Layla is replying', paused: 'Layla is paused', checkConnection: 'Check connection',
  activeOn: 'Layla is replying on {channel}', pausedOn: 'Layla is paused on {channel}', mixedDetail: 'On for {on} · paused on {off}', connectChannel: 'Connect a channel',
  chatLaylaOn: 'Layla is live in this chat', chatLaylaOnHelp: 'Turn off to reply yourself.', chatLaylaOff: 'Layla is stopped in this chat', chatLaylaOffHelp: 'You are replying. Turn on to let Layla answer new messages.',
  broadcasts: 'Broadcasts', view_settings_services: 'Services & prices', view_brain: 'BznsBrain', appointmentRequest: 'Appointment request', appointmentRequests: 'Appointment requests', appointmentFor: 'Appointment request for reception', appointmentPreferences: 'Preferred time', broadcastWhatsAppOnly: 'Broadcasts go out on WhatsApp. Connect a WhatsApp number to message many customers at once.',
  setupReminderTitle: 'Finish setting up Layla', setupReminderBody: 'So Layla can quote your services, and pass a customer to a person when they ask.', setupServices: 'Add your services & prices', setupTeamContact: 'Add a team contact (number or email)',
  channelAttention: '{channel} needs attention', liveTitle: 'Layla is live', liveBody: 'Customers who message you now get an answer straight away. Anything Layla can’t answer waits in your inbox.',
  openInbox: 'Open your inbox', handoffNote: 'Anything Layla can’t answer goes to your inbox, and you can take over any chat at any time.', 
  connectionOk: 'Connection healthy', connectionAttention: 'Connection needs attention', checkedAt: 'Checked {time}', 
  signOut: 'Sign out', setup: 'Business setup', language: 'العربية', loading: 'Loading…', retry: 'Try again', loadMore: 'Load more', close: 'Close', back: 'Back', cancel: 'Cancel',
  save: 'Save', saved: 'Saved', delete: 'Delete', export: 'Export', exportCsv: 'CSV', exportPdf: 'PDF (print)', exportAll: 'Export all (ZIP)', exporting: 'Preparing export…',
  searchChats: 'Search name or number', noChats: 'No conversations yet. When a customer messages your WhatsApp number, the chat appears here.', noResults: 'Nothing matches that search.',
  selectChat: 'Choose a conversation to read it.', you: 'You', layla: 'Layla', yourTeamApp: 'You · WhatsApp app', customer: 'Customer', template: 'Template',
  textExpired: 'Text removed after 30 days', 
  handling: 'Layla stopped', optedOut: 'Opted out', composer: 'Reply to {name}', send: 'Send', sending: 'Sending…', replyPauses: 'Sending a reply stops Layla in this chat.',
  windowClosed: 'The 24-hour reply window closed {time}. WhatsApp only allows an approved template now.', windowClosedWait: 'The 24-hour reply window closed {time}. You can reply as soon as this customer writes again.', sendTemplate: 'Send a template', windowOpen: 'Reply window open until {time}',
  optedOutComposer: 'This customer opted out. You can’t message them from BznsFlow.',
  status_received: 'Received', status_queued: 'Queued', status_attempting: 'Sending', status_submitted: 'Sent to WhatsApp', status_submitted_instagram: 'Sent to Instagram',
  issue_outside_window: 'Not sent: more than 24 hours since the customer last wrote. Wait for them to message again.', issue_recipient_unavailable: 'Not sent: this person can’t receive messages right now.', issue_messages_access_off: 'Not sent: message access for BznsFlow is off in Instagram settings (Messages → Connected tools).', issue_reconnect_required: 'Not sent: the Instagram connection expired. Reconnect Instagram.', issue_rate_limited: 'Not sent: Meta is limiting messages right now. Try again in a few minutes.', issue_invalid_recipient: 'Not sent: Meta did not recognise this customer.', issue_instagram_send_rejected: 'Not sent: Instagram refused this reply.', issue_test_recipient_not_allowed: 'Not sent: this test setup replies only to approved test accounts.', issue_owner_paused: 'Not sent: replies were paused.', issue_window_expired: 'Not sent: the 24-hour reply window had closed.', issue_human_takeover: 'Not sent: you took over this chat.', issue_profile_changed: 'Not sent: your answers changed just before this reply went out. Layla uses the new answers from the next message.', issue_conversation_or_profile_changed: 'Not sent: your answers or this chat changed just before this reply went out. Layla uses the latest answers from the next message.', issue_connection_not_ready: 'Not sent: the connection needs checking.', status_sent: 'Sent', status_delivered: 'Delivered',
  status_read: 'Read', status_failed: 'Not delivered', status_ambiguous: 'Needs checking — not resent', status_blocked: 'Not sent', status_pending: 'Scheduled', status_cancelled: 'Cancelled',
  q_new: 'New', q_in_progress: 'In progress', q_qualified: 'Qualified', q_not_qualified: 'Not qualified', allStatuses: 'All statuses',
  source_inbound: 'Messaged you', source_manual: 'Added by you', source_import: 'Imported', consent_granted: 'Marketing consent', consent_unknown: 'No marketing consent', consent_revoked: 'Consent withdrawn',
  name_owner: 'Your edit', name_customer: 'Told Layla', name_whatsapp: 'WhatsApp name', name_number: 'Number only',
  searchContacts: 'Search contacts', addContacts: 'Add or import', noContacts: 'No contacts yet.', lastActivity: 'Last activity', number: 'Number', name: 'Name', status: 'Status', details: 'Details',
  source: 'Source', consent: 'Consent', takeover: 'Chat', openChat: 'Open chat', editContact: 'Edit contact', ownerName: 'Name (your edit)', overrideStatus: 'Qualification',
  automatic: 'Automatic ({status})', captured: 'Captured by Layla', fromOwner: 'Your edit', deleteContact: 'Delete contact', deleteConfirm: 'Delete {name}? Their readable details and chat text are removed. If they opted out, that choice is kept so they are never messaged again.',
  deleteNow: 'Delete permanently', contactDeleted: 'Contact deleted.', fieldsHeading: 'Lead details', migrationPending: 'Older chats are still being linked to contacts. Refresh in a moment.',
  broadcastIntro: 'Send an approved WhatsApp marketing template to customers who agreed to receive it.', templates: 'Templates', syncTemplates: 'Sync approved templates', syncing: 'Syncing…',
  lastSynced: 'Last synced {time}', neverSynced: 'Not synced yet', manageTemplates: 'Create or edit templates in WhatsApp Manager', noTemplates: 'No approved templates yet. Create one in WhatsApp Manager, wait for Meta to approve it, then press Sync templates.',
  unsupported: 'Can’t be sent here', unsupported_media_header: 'Media header', unsupported_dynamic_button: 'Button needs a variable', unsupported_unsupported_component: 'Unsupported layout', unsupported_invalid_variables: 'Variables out of order', unsupported_not_approved: 'Not approved', unsupported_not_marketing: 'Not marketing', unsupported_missing_body: 'No body text',
  newBroadcast: 'New broadcast', campaigns: 'Broadcasts', noCampaigns: 'No broadcasts yet.', cancelBroadcast: 'Cancel broadcast', scheduledFor: 'Scheduled for {time}', recipients: 'Recipients',
  camp_scheduled: 'Scheduled', camp_starting: 'Starting', camp_processing: 'Sending', camp_completed: 'Finished', camp_cancelled: 'Cancelled', camp_blocked: 'Stopped',
  broadcastUnavailable: 'Sending broadcasts is not switched on yet. Your approved templates are in Broadcasts.', broadcastSendingOff: 'Sending is not switched on yet. Create templates in WhatsApp Manager and sync them here; they are ready the moment sending is on.',
  step_template: 'Template', step_recipients: 'Numbers', step_send: 'Send', next: 'Continue', previous: 'Back',
  chooseTemplate: 'Choose an approved template', variable: 'Variable {key}', variableSource: 'Fill with', source_static: 'Same text for everyone', source_name: 'Customer’s name', source_field: 'Lead detail: {field}',
  source_column: 'Column: {column}', source_each: 'Type it for each customer', textForAll: 'Text for everyone', fillWith: 'Fill each variable', uploadList: 'Upload list', typeNumbers: 'Type numbers',
  broadcastSteps: 'Choose a template, add numbers or upload a list, then send.', uploadHelp: 'CSV or XLSX: a phone column, a name column, and one column per template variable.',
  addToList: 'Add {count} to the list', addedRows: '{added} added · {duplicates} already in the list', overLimit: '{count} left out: up to {max} numbers per broadcast.',
  emptyList: 'No numbers yet. Type them, upload a list or pick saved contacts.', listCount: '{count} / {max} numbers', whoReceives: 'Who receives it', removeRow: 'Remove {number}',
  missingCells: '{count} rows have an empty variable. Fill the marked cells or remove those rows.', removeIncomplete: 'Remove incomplete rows', savingNumbers: 'Saving numbers…',
  consentHow: 'How did they agree?', consent_whatsapp: 'They messaged us on WhatsApp', consent_store: 'They signed up in store', consent_website: 'They signed up on our website', consent_other: 'Another way',
  consentOther: 'Describe how they agreed', previewOf: '{n} of {total}', prevContact: 'Previous customer', nextContact: 'Next customer', messageFor: 'Message for {name}',
  sendingOffShort: 'Sending is not switched on yet. You can check every message, but not send it.', when: 'When',
  notWhatsApp: '{count} landline, toll-free or non-mobile skipped', column_type: 'Number type column', not_mobile: 'This is not a mobile number, so it cannot have WhatsApp.',
  reason_not_on_whatsapp: 'WhatsApp couldn’t deliver to this number before', reason_wrong_channel: 'Instagram contact',
  fallback: 'If empty, use', value: 'Text', preview: 'Preview', savedContacts: 'Saved contacts', manualEntry: 'Type numbers', importFile: 'Import file', selected: '{count} selected',
  eligibleOnly: 'Only contacts with marketing consent can be selected.', addNumber: 'Add number', country: 'Country', nationalNumber: 'Phone number', contactName: 'Name (optional)',
  consentTitle: 'Marketing consent', consentIntro: 'Confirm how these customers agreed to receive marketing messages from your business. This record is saved with every contact.',
  consentSource: 'How they agreed', consentSourceHint: 'For example: in-store sign-up form, website checkbox', consentDate: 'Date they agreed', consentPurpose: 'What they agreed to receive', consentPurposeHint: 'For example: monthly offers and new products',
  consentAttest: 'I confirm each of these customers gave my business permission to send them marketing messages on WhatsApp, and none of them has withdrawn it.',
  sendNow: 'Send now', sendLater: 'Schedule for later', scheduleAt: 'Date and time', timezone: 'Business timezone', reviewEligible: '{count} will receive it', reviewExcluded: '{count} excluded',
  cap: 'Up to {cap} recipients per broadcast (WhatsApp allowance {allowance}).', confirmSend: 'Send to {count} now', confirmSchedule: 'Schedule for {count}', broadcastCreated: 'Broadcast saved.',
  reason_consent_unknown: 'No consent recorded', reason_consent_revoked: 'Consent withdrawn', reason_opted_out: 'Opted out', reason_contact_deleted: 'Deleted', reason_missing_variable: 'Missing a variable',
  usWarning: '+1 numbers in the US don’t receive WhatsApp marketing templates.', importTitle: 'Import contacts', importHelp: 'CSV or XLSX, up to 1,000 rows. Nothing is sent during import.',
  downloadSample: 'Download a sample file', chooseFile: 'Choose file', mapColumns: 'Match your columns', column_phone: 'Phone column', column_name: 'Name column', column_country: 'Country column',
  noColumn: 'Not in file', defaultCountry: 'Country for numbers without a code', importPreview: '{valid} ready · {duplicates} duplicates merged · {invalid} need fixing', importRowIssue: 'Row {line}: {reason}',
  invalid_phone: 'not a valid number', missing_phone: 'no number', missing_country: 'needs a country', importNow: 'Import {count} contacts', imported: '{created} added, {updated} updated.',
  truncated: 'Only the first 1,000 rows are imported.', consentOptional: 'Also record marketing consent for these contacts', 
  dashboardUnavailable: 'The dashboard isn’t switched on yet. Your setup and Layla’s replies are unaffected.',
  view_accounts: 'Accounts and VAT', capturedNone: 'Layla hasn’t captured any details from this chat yet.', openRecord: 'Open contact',
  textCleared: 'Text cleared after 24 hours', textClearedHelp: 'For patients’ privacy, message text is erased after 24 hours. What Layla captured stays.',
};
const ar = {
  title: 'لوحة ليلى', loadEarlier: 'عرض الرسائل الأقدم', nav: 'أقسام اللوحة', today: 'اليوم', money: 'المال', customers: 'العملاء', settings: 'الإعدادات', sectionViews: 'أقسام هذه الصفحة',
  view_products: 'المنتجات', view_services: 'الخدمات', view_insights: 'الملخص', view_expenses: 'المصروفات', view_contacts: 'قائمة العملاء', view_broadcast: 'رسالة جماعية', view_channels: 'القنوات', view_business: 'بيانات النشاط',
  broadcast: 'الرسائل الجماعية', chats: 'المحادثات', contacts: 'جهات الاتصال', business: 'نشاطك',
  active: 'ليلى ترد الآن', paused: 'ليلى متوقفة', checkConnection: 'فحص الاتصال',
  activeOn: 'ليلى ترد الآن على {channel}', pausedOn: 'ليلى متوقفة على {channel}', mixedDetail: 'تعمل على {on} · متوقفة على {off}', connectChannel: 'اربط قناة',
  chatLaylaOn: 'ليلى تعمل في هذه المحادثة', chatLaylaOnHelp: 'أوقفها لترد بنفسك.', chatLaylaOff: 'ليلى متوقفة في هذه المحادثة', chatLaylaOffHelp: 'أنت من يرد الآن. شغّلها لترد ليلى على الرسائل الجديدة.',
  broadcasts: 'الرسائل الجماعية', view_settings_services: 'الخدمات والأسعار', view_brain: 'BznsBrain', appointmentRequest: 'طلب موعد', appointmentRequests: 'طلبات المواعيد', appointmentFor: 'طلب موعد للاستقبال', appointmentPreferences: 'الوقت المفضل', broadcastWhatsAppOnly: 'تُرسل الرسائل الجماعية عبر واتساب. اربط رقم واتساب لمراسلة عملاء كثيرين دفعة واحدة.',
  setupReminderTitle: 'أكمل إعداد ليلى', setupReminderBody: 'لتعرض ليلى خدماتك، وتحوّل العميل إلى شخص من فريقك عندما يطلب.', setupServices: 'أضف خدماتك وأسعارها', setupTeamContact: 'أضف وسيلة تواصل مع فريقك (رقم أو بريد)',
  channelAttention: '{channel} يحتاج مراجعة', liveTitle: 'ليلى تعمل الآن', liveBody: 'كل عميل يراسلك الآن يحصل على رد فوري. وما لا تعرف ليلى إجابته ينتظرك في المحادثات.',
  openInbox: 'افتح المحادثات', handoffNote: 'ما لا تعرف ليلى إجابته يصل إلى محادثاتك، ويمكنك استلام أي محادثة في أي وقت.', 
  connectionOk: 'الاتصال سليم', connectionAttention: 'الاتصال يحتاج مراجعة', checkedAt: 'آخر فحص {time}', 
  signOut: 'تسجيل الخروج', setup: 'إعداد النشاط', language: 'English', loading: 'جارٍ التحميل…', retry: 'حاول مجدداً', loadMore: 'عرض المزيد', close: 'إغلاق', back: 'رجوع', cancel: 'إلغاء',
  save: 'حفظ', saved: 'تم الحفظ', delete: 'حذف', export: 'تصدير', exportCsv: 'CSV', exportPdf: 'PDF (طباعة)', exportAll: 'تصدير الكل (ZIP)', exporting: 'جارٍ تجهيز الملف…',
  searchChats: 'ابحث بالاسم أو الرقم', noChats: 'لا توجد محادثات بعد. عندما يراسل عميل رقم واتساب نشاطك ستظهر المحادثة هنا.', noResults: 'لا توجد نتائج مطابقة.',
  selectChat: 'اختر محادثة لقراءتها.', you: 'أنت', layla: 'ليلى', yourTeamApp: 'أنت · تطبيق واتساب', customer: 'العميل', template: 'قالب',
  textExpired: 'حُذف النص بعد ٣٠ يوماً', 
  handling: 'ليلى متوقفة', optedOut: 'ألغى الاشتراك', composer: 'رد على {name}', send: 'إرسال', sending: 'جارٍ الإرسال…', replyPauses: 'إرسال رد يوقف ليلى في هذه المحادثة.',
  windowClosed: 'انتهت نافذة الرد (٢٤ ساعة) {time}. يسمح واتساب الآن بقالب معتمد فقط.', windowClosedWait: 'انتهت نافذة الرد (٢٤ ساعة) {time}. يمكنك الرد فور أن يراسلك هذا العميل مجدداً.', sendTemplate: 'إرسال قالب', windowOpen: 'نافذة الرد مفتوحة حتى {time}',
  optedOutComposer: 'ألغى هذا العميل الاشتراك. لا يمكنك مراسلته من BznsFlow.',
  status_received: 'مستلمة', status_queued: 'في الانتظار', status_attempting: 'جارٍ الإرسال', status_submitted: 'أُرسلت إلى واتساب', status_submitted_instagram: 'أُرسلت إلى إنستغرام',
  issue_outside_window: 'لم تُرسل: مرّت أكثر من ٢٤ ساعة منذ آخر رسالة من العميل. انتظر رسالته التالية.', issue_recipient_unavailable: 'لم تُرسل: لا يمكن لهذا الشخص استقبال الرسائل الآن.', issue_messages_access_off: 'لم تُرسل: وصول BznsFlow إلى الرسائل متوقف في إعدادات إنستغرام (الرسائل ← الأدوات المتصلة).', issue_reconnect_required: 'لم تُرسل: انتهت صلاحية ربط إنستغرام. أعد الربط.', issue_rate_limited: 'لم تُرسل: Meta تحدّ من الرسائل حالياً. حاول بعد دقائق.', issue_invalid_recipient: 'لم تُرسل: لم تتعرّف Meta على هذا العميل.', issue_instagram_send_rejected: 'لم تُرسل: رفض إنستغرام هذا الرد.', issue_test_recipient_not_allowed: 'لم تُرسل: إعداد الاختبار هذا يرد على حسابات الاختبار المعتمدة فقط.', issue_owner_paused: 'لم تُرسل: الردود متوقفة.', issue_window_expired: 'لم تُرسل: انتهت نافذة الرد البالغة ٢٤ ساعة.', issue_human_takeover: 'لم تُرسل: توليت هذه المحادثة بنفسك.', issue_profile_changed: 'لم تُرسل: تغيّرت إجاباتك قبل إرسال هذا الرد مباشرة. تستخدم ليلى الإجابات الجديدة من الرسالة التالية.', issue_conversation_or_profile_changed: 'لم تُرسل: تغيّرت إجاباتك أو هذه المحادثة قبل إرسال الرد مباشرة. تستخدم ليلى أحدث الإجابات من الرسالة التالية.', issue_connection_not_ready: 'لم تُرسل: الاتصال يحتاج إلى فحص.', status_sent: 'أُرسلت', status_delivered: 'وصلت',
  status_read: 'قُرئت', status_failed: 'لم تصل', status_ambiguous: 'تحتاج تحققاً — لم يُعد إرسالها', status_blocked: 'لم تُرسل', status_pending: 'مجدولة', status_cancelled: 'أُلغيت',
  q_new: 'جديد', q_in_progress: 'قيد التأهيل', q_qualified: 'مؤهل', q_not_qualified: 'غير مؤهل', allStatuses: 'كل الحالات',
  source_inbound: 'راسلك', source_manual: 'أضفته أنت', source_import: 'مستورد', consent_granted: 'موافق على التسويق', consent_unknown: 'لا توجد موافقة تسويق', consent_revoked: 'سحب الموافقة',
  name_owner: 'تعديلك', name_customer: 'أخبر ليلى', name_whatsapp: 'اسم واتساب', name_number: 'رقم فقط',
  searchContacts: 'ابحث في جهات الاتصال', addContacts: 'إضافة أو استيراد', noContacts: 'لا توجد جهات اتصال بعد.', lastActivity: 'آخر نشاط', number: 'الرقم', name: 'الاسم', status: 'الحالة', details: 'التفاصيل',
  source: 'المصدر', consent: 'الموافقة', takeover: 'المحادثة', openChat: 'فتح المحادثة', editContact: 'تعديل جهة الاتصال', ownerName: 'الاسم (تعديلك)', overrideStatus: 'التأهيل',
  automatic: 'تلقائي ({status})', captured: 'جمعته ليلى', fromOwner: 'تعديلك', deleteContact: 'حذف جهة الاتصال', deleteConfirm: 'حذف {name}؟ تُحذف بياناته ونصوص محادثته. إذا ألغى الاشتراك يبقى اختياره محفوظاً حتى لا يُراسَل مجدداً.',
  deleteNow: 'حذف نهائي', contactDeleted: 'حُذفت جهة الاتصال.', fieldsHeading: 'تفاصيل العميل المحتمل', migrationPending: 'ما زال ربط المحادثات القديمة بجهات الاتصال جارياً. حدّث الصفحة بعد قليل.',
  broadcastIntro: 'أرسل قالب تسويق معتمداً على واتساب إلى العملاء الذين وافقوا على استلامه.', templates: 'القوالب', syncTemplates: 'مزامنة القوالب المعتمدة', syncing: 'جارٍ المزامنة…',
  lastSynced: 'آخر مزامنة {time}', neverSynced: 'لم تتم المزامنة بعد', manageTemplates: 'أنشئ القوالب أو عدّلها في مدير واتساب', noTemplates: 'لا توجد قوالب معتمدة بعد. أنشئ قالباً في مدير واتساب، وانتظر موافقة Meta، ثم اضغط مزامنة القوالب.',
  unsupported: 'لا يمكن إرساله هنا', unsupported_media_header: 'رأس وسائط', unsupported_dynamic_button: 'زر يحتاج متغيراً', unsupported_unsupported_component: 'تصميم غير مدعوم', unsupported_invalid_variables: 'ترتيب المتغيرات غير صحيح', unsupported_not_approved: 'غير معتمد', unsupported_not_marketing: 'ليس تسويقياً', unsupported_missing_body: 'بلا نص',
  newBroadcast: 'رسالة جماعية جديدة', campaigns: 'الرسائل الجماعية', noCampaigns: 'لا توجد رسائل جماعية بعد.', cancelBroadcast: 'إلغاء الإرسال', scheduledFor: 'مجدولة في {time}', recipients: 'المستلمون',
  camp_scheduled: 'مجدولة', camp_starting: 'تبدأ', camp_processing: 'جارٍ الإرسال', camp_completed: 'اكتملت', camp_cancelled: 'أُلغيت', camp_blocked: 'توقفت',
  broadcastUnavailable: 'إرسال الرسائل الجماعية غير مفعّل بعد. قوالبك المعتمدة في صفحة الرسائل الجماعية.', broadcastSendingOff: 'الإرسال غير مفعّل بعد. أنشئ القوالب في مدير واتساب وزامنها هنا، وتكون جاهزة فور تفعيل الإرسال.',
  step_template: 'القالب', step_recipients: 'الأرقام', step_send: 'الإرسال', next: 'متابعة', previous: 'رجوع',
  chooseTemplate: 'اختر قالباً معتمداً', variable: 'المتغير {key}', variableSource: 'املأه بـ', source_static: 'نص واحد للجميع', source_name: 'اسم العميل', source_field: 'تفصيل العميل: {field}',
  source_column: 'العمود: {column}', source_each: 'أكتبه لكل عميل', textForAll: 'النص للجميع', fillWith: 'املأ كل متغير', uploadList: 'رفع قائمة', typeNumbers: 'كتابة أرقام',
  broadcastSteps: 'اختر قالباً، وأضف الأرقام أو ارفع قائمة، ثم أرسل.', uploadHelp: 'ملف CSV أو XLSX: عمود للرقم، وعمود للاسم، وعمود لكل متغير في القالب.',
  addToList: 'إضافة {count} إلى القائمة', addedRows: 'أُضيف {added} · {duplicates} موجود مسبقاً', overLimit: 'لم يُضف {count}: الحد {max} رقم لكل رسالة جماعية.',
  emptyList: 'لا توجد أرقام بعد. اكتبها، أو ارفع قائمة، أو اختر من الجهات المحفوظة.', listCount: '{count} / {max} رقم', whoReceives: 'من يستلمها', removeRow: 'إزالة {number}',
  missingCells: '{count} صفوف فيها متغير فارغ. املأ الخانات المعلّمة أو أزل هذه الصفوف.', removeIncomplete: 'إزالة الصفوف الناقصة', savingNumbers: 'جارٍ حفظ الأرقام…',
  consentHow: 'كيف وافقوا؟', consent_whatsapp: 'راسلونا على واتساب', consent_store: 'سجّلوا في المحل', consent_website: 'سجّلوا في موقعنا', consent_other: 'طريقة أخرى',
  consentOther: 'صف كيف وافقوا', previewOf: '{n} من {total}', prevContact: 'العميل السابق', nextContact: 'العميل التالي', messageFor: 'رسالة {name}',
  sendingOffShort: 'الإرسال غير مفعّل بعد. يمكنك مراجعة كل رسالة، لكن لا يمكن إرسالها.', when: 'التوقيت',
  notWhatsApp: 'تم تخطي {count} رقم أرضي أو مجاني أو غير جوال', column_type: 'عمود نوع الرقم', not_mobile: 'هذا ليس رقم جوال، فلا يمكن أن يكون عليه واتساب.',
  reason_not_on_whatsapp: 'تعذّر على واتساب التوصيل لهذا الرقم سابقاً', reason_wrong_channel: 'جهة اتصال إنستغرام',
  fallback: 'إن كان فارغاً استخدم', value: 'النص', preview: 'معاينة', savedContacts: 'جهات محفوظة', manualEntry: 'كتابة أرقام', importFile: 'استيراد ملف', selected: 'تم اختيار {count}',
  eligibleOnly: 'يمكن اختيار جهات الاتصال التي وافقت على التسويق فقط.', addNumber: 'إضافة الرقم', country: 'الدولة', nationalNumber: 'رقم الهاتف', contactName: 'الاسم (اختياري)',
  consentTitle: 'موافقة التسويق', consentIntro: 'أكّد كيف وافق هؤلاء العملاء على استلام رسائل تسويقية من نشاطك. يُحفظ هذا السجل مع كل جهة اتصال.',
  consentSource: 'كيف وافقوا', consentSourceHint: 'مثال: نموذج اشتراك في المحل، خانة في الموقع', consentDate: 'تاريخ الموافقة', consentPurpose: 'ما الذي وافقوا على استلامه', consentPurposeHint: 'مثال: العروض الشهرية والمنتجات الجديدة',
  consentAttest: 'أؤكد أن كل هؤلاء العملاء منحوا نشاطي إذناً بإرسال رسائل تسويقية لهم على واتساب، ولم يسحبه أي منهم.',
  sendNow: 'إرسال الآن', sendLater: 'جدولة لاحقاً', scheduleAt: 'التاريخ والوقت', timezone: 'المنطقة الزمنية للنشاط', reviewEligible: 'سيستلمها {count}', reviewExcluded: 'استُبعد {count}',
  cap: 'حتى {cap} مستلم لكل رسالة جماعية (حد واتساب {allowance}).', confirmSend: 'إرسال إلى {count} الآن', confirmSchedule: 'جدولة لـ {count}', broadcastCreated: 'حُفظت الرسالة الجماعية.',
  reason_consent_unknown: 'لا توجد موافقة مسجلة', reason_consent_revoked: 'سحب الموافقة', reason_opted_out: 'ألغى الاشتراك', reason_contact_deleted: 'محذوف', reason_missing_variable: 'ينقصه متغير',
  usWarning: 'أرقام +1 في الولايات المتحدة لا تستلم قوالب التسويق على واتساب.', importTitle: 'استيراد جهات اتصال', importHelp: 'ملف CSV أو XLSX حتى ١٠٠٠ صف. لا يُرسل أي شيء أثناء الاستيراد.',
  downloadSample: 'تنزيل ملف نموذجي', chooseFile: 'اختر ملفاً', mapColumns: 'طابق الأعمدة', column_phone: 'عمود الهاتف', column_name: 'عمود الاسم', column_country: 'عمود الدولة',
  noColumn: 'غير موجود في الملف', defaultCountry: 'الدولة للأرقام بدون رمز', importPreview: '{valid} جاهز · {duplicates} مكرر دُمج · {invalid} تحتاج تصحيحاً', importRowIssue: 'الصف {line}: {reason}',
  invalid_phone: 'رقم غير صالح', missing_phone: 'بلا رقم', missing_country: 'يحتاج دولة', importNow: 'استيراد {count} جهة اتصال', imported: 'أُضيف {created}، وحُدّث {updated}.',
  truncated: 'يُستورد أول ١٠٠٠ صف فقط.', consentOptional: 'سجّل أيضاً موافقة التسويق لهذه الجهات', 
  dashboardUnavailable: 'اللوحة غير مفعّلة بعد. إعدادك وردود ليلى لا تتأثر.',
  view_accounts: 'الحسابات والضريبة', capturedNone: 'لم تسجّل ليلى أي تفاصيل من هذه المحادثة بعد.', openRecord: 'افتح جهة الاتصال',
  textCleared: 'حُذف النص بعد 24 ساعة', textClearedHelp: 'حفاظاً على خصوصية المرضى، يُحذف نص الرسائل بعد 24 ساعة. ما سجّلته ليلى يبقى.',
};

// One industry's own words for the shared dashboard screens (keys exist in both tables above).
const PACK_WORDS = {
  dental: {
    en: { customers: 'Patients', contacts: 'Patients', customer: 'Patient', view_contacts: 'Patient list', view_products: 'Supplies', view_services: 'Treatments', openRecord: 'Open patient', textExpired: 'Text cleared after 24 hours' },
    ar: { customers: 'المرضى', contacts: 'المرضى', customer: 'المريض', view_contacts: 'قائمة المرضى', view_products: 'المستلزمات', view_services: 'العلاجات', openRecord: 'افتح ملف المريض', textExpired: 'حُذف النص بعد 24 ساعة' },
  },
};

const reasons = {
  en: { sign_in_required: 'Sign in again to continue.', setup_required: 'Finish your business setup first.', connection_not_ready: 'WhatsApp connection needs attention. Check the connection, then try again.',
    reply_not_allowed: 'A reply needs a message from this customer in the last 24 hours.', window_closed: 'The 24-hour reply window has closed. WhatsApp only allows an approved template now.', contact_opted_out: 'This customer opted out, so they can’t be messaged from BznsFlow.', messaging_paused_by_operator: 'Sending is paused by BznsFlow for maintenance. Your reply was not sent; try again shortly.', invalid_text: 'Write a reply up to 1,000 characters (on Instagram, about 500 in Arabic).', conversation_not_found: 'This chat is no longer available.',
    contact_not_found: 'This contact is no longer available.', invalid_contact_field: 'One of the details isn’t in the expected format.', template_not_sendable: 'That template can’t be sent. Sync templates and choose another.',
    invalid_mapping: 'Fill in every template variable.', no_eligible_recipients: 'None of the selected contacts can receive marketing messages.', recipient_limit: 'Choose 100 recipients or fewer.',
    messaging_limit: 'That’s more than WhatsApp currently allows for this number today. Choose fewer recipients.', invalid_schedule: 'Choose a valid time within the next 30 days.',
    campaign_not_cancellable: 'Sending has already started, so it can’t be cancelled.', broadcast_unavailable: 'Broadcast is not switched on yet.', consent_required: 'Record the marketing consent to continue.',
    invalid_consent: 'Complete every consent field with a date that isn’t in the future.', invalid_import: 'The import couldn’t be read. Check the file and try again.', invalid_phone: 'One of the numbers isn’t valid.',
    refresh_throttled: 'Please wait a few seconds before checking again.', send_outcome_unknown: 'A reply needs checking before Layla can restart.', activation_not_ready: 'Save your business details, then check the connection and try again.',
    import_file_too_large: 'Use a file under 5 MB.', import_file_type: 'Use a CSV or XLSX file.', import_file_empty: 'The file has no rows.', dashboard_unavailable: 'The dashboard isn’t available right now.',
    access_required: 'Your account needs product access. Ask your administrator to grant access.',
    handoff_changed: 'This conversation changed. Reload it before trying again.', takeover_required: 'Stop Layla in this chat before resolving it.',
    plan_required: 'This isn’t included in your plan. Contact BznsFlow to add it.', manager_required: 'Only the account manager can do this.',
    confirmation_required: 'Confirm to continue.', workspace_access_revoked: 'Your access to this business was removed. Ask the manager to invite you again.',
    session_expired: 'Your session expired. Sign in again to continue.', csrf: 'This page is out of date. Refresh the page and try again.', origin: 'This page is out of date. Refresh the page and try again.',
    body_too_large: 'That’s too much to send at once. Shorten it or send it in parts.', invalid_action: 'This page is out of date. Refresh the page and try again.',
    invalid_timezone: 'Choose a valid time zone.', invalid_search: 'Use a shorter search (up to 80 characters).', messaging_unavailable: 'Messaging is switched off for now. Nothing was sent.',
    account_unavailable: 'Accounts are unavailable right now. Try again in a few minutes.', send_failed: 'We couldn’t send that email. Try again in a few minutes.',
    echo_pending: 'A reply from your WhatsApp app is still being recorded. Wait a few seconds, then try again.', profile_changed: 'Your business answers changed while this was open. Refresh the page, then try again.',
    instagram_reconnect_required: 'Instagram needs to be reconnected. Open Settings → Channels and connect it again.', instagram_subscription_failed: 'Instagram didn’t confirm message access. In the Instagram app allow access to messages, then try again.' },
  ar: { sign_in_required: 'سجّل الدخول مجدداً للمتابعة.', setup_required: 'أكمل إعداد نشاطك أولاً.', connection_not_ready: 'اتصال واتساب يحتاج مراجعة. افحص الاتصال ثم حاول مجدداً.',
    reply_not_allowed: 'يتطلب الرد رسالة من هذا العميل خلال آخر ٢٤ ساعة.', window_closed: 'انتهت نافذة الرد (٢٤ ساعة). يسمح واتساب الآن بقالب معتمد فقط.', contact_opted_out: 'ألغى هذا العميل الاشتراك، ولا يمكن مراسلته من BznsFlow.', messaging_paused_by_operator: 'الإرسال متوقف مؤقتاً من BznsFlow للصيانة. لم يُرسل ردك؛ حاول بعد قليل.', invalid_text: 'اكتب رداً حتى ١٠٠٠ حرف (على إنستغرام نحو ٥٠٠ حرف بالعربية).', conversation_not_found: 'هذه المحادثة لم تعد متاحة.',
    contact_not_found: 'جهة الاتصال هذه لم تعد متاحة.', invalid_contact_field: 'أحد التفاصيل ليس بالصيغة المتوقعة.', template_not_sendable: 'لا يمكن إرسال هذا القالب. زامن القوالب واختر غيره.',
    invalid_mapping: 'املأ كل متغيرات القالب.', no_eligible_recipients: 'لا يمكن لأي من الجهات المختارة استلام رسائل تسويقية.', recipient_limit: 'اختر ١٠٠ مستلم أو أقل.',
    messaging_limit: 'العدد أكبر مما يسمح به واتساب لهذا الرقم اليوم. اختر عدداً أقل.', invalid_schedule: 'اختر وقتاً صالحاً خلال الثلاثين يوماً القادمة.',
    campaign_not_cancellable: 'بدأ الإرسال بالفعل ولا يمكن إلغاؤه.', broadcast_unavailable: 'الرسائل الجماعية غير مفعّلة بعد.', consent_required: 'سجّل موافقة التسويق للمتابعة.',
    invalid_consent: 'أكمل كل حقول الموافقة بتاريخ ليس في المستقبل.', invalid_import: 'تعذّرت قراءة الاستيراد. تحقق من الملف وحاول مجدداً.', invalid_phone: 'أحد الأرقام غير صالح.',
    refresh_throttled: 'انتظر بضع ثوانٍ قبل الفحص مجدداً.', send_outcome_unknown: 'يحتاج رد إلى تحقق قبل إعادة تشغيل ليلى.', activation_not_ready: 'احفظ تفاصيل نشاطك، ثم افحص الاتصال وحاول مجدداً.',
    import_file_too_large: 'استخدم ملفاً أصغر من ٥ ميجابايت.', import_file_type: 'استخدم ملف CSV أو XLSX.', import_file_empty: 'الملف لا يحتوي على صفوف.', dashboard_unavailable: 'اللوحة غير متاحة حالياً.',
    access_required: 'حسابك يحتاج إلى صلاحية استخدام المنتج. اطلب من المسؤول منحك الوصول.',
    handoff_changed: 'تغيّرت المحادثة. أعد تحميلها قبل المحاولة مجدداً.', takeover_required: 'أوقف ليلى في هذه المحادثة قبل إنهاء المتابعة.',
    plan_required: 'هذه الميزة غير مشمولة في باقتك. تواصل مع BznsFlow لإضافتها.', manager_required: 'هذا الإجراء متاح لمدير الحساب فقط.',
    confirmation_required: 'أكّد للمتابعة.', workspace_access_revoked: 'أُلغي وصولك إلى هذا النشاط. اطلب من المدير دعوتك مجدداً.',
    session_expired: 'انتهت جلستك. سجّل الدخول مجدداً للمتابعة.', csrf: 'هذه الصفحة قديمة. حدّث الصفحة وحاول مجدداً.', origin: 'هذه الصفحة قديمة. حدّث الصفحة وحاول مجدداً.',
    body_too_large: 'المحتوى أكبر من المسموح في مرة واحدة. اختصره أو أرسله على أجزاء.', invalid_action: 'هذه الصفحة قديمة. حدّث الصفحة وحاول مجدداً.',
    invalid_timezone: 'اختر منطقة زمنية صالحة.', invalid_search: 'استخدم بحثاً أقصر (حتى ٨٠ حرفاً).', messaging_unavailable: 'المراسلة متوقفة حالياً. لم يُرسل شيء.',
    account_unavailable: 'الحسابات غير متاحة حالياً. حاول بعد بضع دقائق.', send_failed: 'تعذّر إرسال البريد. حاول بعد بضع دقائق.',
    echo_pending: 'ما زال يُسجَّل رد أُرسل من تطبيق واتساب. انتظر بضع ثوانٍ ثم حاول مجدداً.', profile_changed: 'تغيّرت إجابات نشاطك أثناء فتح هذه الصفحة. حدّث الصفحة ثم حاول مجدداً.',
    instagram_reconnect_required: 'يجب إعادة ربط إنستغرام. افتح الإعدادات ← القنوات واربطه مجدداً.', instagram_subscription_failed: 'لم يؤكد إنستغرام صلاحية الرسائل. اسمح بالوصول إلى الرسائل في تطبيق إنستغرام ثم حاول مجدداً.' },
};

// Instagram's own wording for the same codes: what to do in Instagram, not in WhatsApp.
const instagramReasons = {
  en: {
    activation_not_ready: 'Save your business details, then check the connection and try again.',
    instagram_reconnect_required: 'Instagram needs reconnecting. Click Reconnect Instagram.',
    connection_not_ready: 'Meta is not delivering this account’s messages to BznsFlow yet. In Instagram turn on Allow access to messages, then click Reconnect Instagram.',
    send_outcome_unknown: 'A reply needs checking before replies can restart. Open the inbox to review it.',
    sign_in_required: 'Your session ended. Sign in again.',
    connection_busy: 'BznsFlow is still removing this Instagram account’s data. It takes a few seconds; try again shortly.',
    too_soon: 'Please wait a few seconds before trying again.',
    instagram_permissions_missing: 'Grant both requested Instagram permissions and reconnect.',
    messaging_unavailable: 'Instagram replies are not enabled yet.',
    asset_in_use: 'This Instagram account is connected to another BznsFlow account.',
    instagram_rate_limited: 'Meta is limiting how often BznsFlow can check Instagram. Nothing is broken; try again in a few minutes.',
    instagram_provider_unavailable: 'Instagram did not respond. Nothing changed; try again in a minute.',
    instagram_provider_failed: 'Instagram did not respond. Nothing changed; try again in a minute.',
  },
  ar: {
    activation_not_ready: 'احفظ تفاصيل نشاطك، ثم افحص الاتصال وحاول مجدداً.',
    instagram_reconnect_required: 'يحتاج إنستغرام إلى إعادة الربط. اضغط «إعادة ربط إنستغرام».',
    connection_not_ready: 'لا توصل Meta رسائل هذا الحساب إلى BznsFlow بعد. فعّل «السماح بالوصول إلى الرسائل» في إنستغرام ثم اضغط «إعادة ربط إنستغرام».',
    send_outcome_unknown: 'هناك رد يحتاج إلى مراجعة قبل استئناف الردود. افتح المحادثات لمراجعته.',
    sign_in_required: 'انتهت جلستك. سجّل الدخول مجدداً.',
    connection_busy: 'ما زال BznsFlow يحذف بيانات حساب إنستغرام هذا. يستغرق ذلك بضع ثوانٍ؛ حاول مجدداً بعد قليل.',
    too_soon: 'انتظر بضع ثوانٍ قبل المحاولة مجدداً.',
    instagram_permissions_missing: 'امنح إذني إنستغرام المطلوبين وأعد الربط.',
    messaging_unavailable: 'ردود إنستغرام غير مفعّلة بعد.',
    asset_in_use: 'حساب إنستغرام مرتبط بحساب آخر في BznsFlow.',
    instagram_rate_limited: 'تحدّ Meta من عدد مرات فحص إنستغرام من BznsFlow. لا يوجد عطل؛ حاول مجدداً بعد بضع دقائق.',
    instagram_provider_unavailable: 'لم يستجب إنستغرام. لم يتغير شيء؛ حاول مجدداً بعد دقيقة.',
    instagram_provider_failed: 'لم يستجب إنستغرام. لم يتغير شيء؛ حاول مجدداً بعد دقيقة.',
  },
};

/** @param {string} lang @param {string} [packId] the Hasib industry, whose own words replace the defaults */
export function createStrings(lang, packId) {
  const words = PACK_WORDS[packId], table = { ...(lang === 'ar' ? ar : en), ...(words ? words[lang === 'ar' ? 'ar' : 'en'] : {}) };
  const t = (key, vars = {}) => String(table[key] ?? en[key] ?? key).replace(/\{(\w+)\}/g, (m, name) => (vars[name] ?? m));
  // `channel` picks Instagram's wording where it differs; every other code uses the shared table.
  const reason = (code, channel) => (channel === 'instagram' ? instagramReasons[lang === 'ar' ? 'ar' : 'en'][code] : undefined)
    || (lang === 'ar' ? reasons.ar : reasons.en)[code] || (lang === 'ar' ? 'تعذّر إكمال الخطوة. حاول مجدداً.' : 'That didn’t work. Please try again.');
  return { t, reason, lang, ar: lang === 'ar', packId: packId || null };
}
/** "Submitted" names the channel Meta accepted the message on. */
/** A plain-language reason for a message that was not sent, or null for unknown reasons. */
export const issueKey = reason => (reason && Object.hasOwn(en, `issue_${reason}`) ? `issue_${reason}` : null);
export const statusKey = (status, channel) => status === 'submitted' && channel === 'instagram' ? 'status_submitted_instagram' : `status_${status}`;
export const STRING_KEYS = Object.keys(en);
export const ARABIC_KEYS = Object.keys(ar);
export const PACK_WORD_KEYS = Object.fromEntries(Object.entries(PACK_WORDS).map(([id, w]) => [id, { en: Object.keys(w.en), ar: Object.keys(w.ar) }]));
