import React, { useEffect, useState } from 'react';
import { readCatalogFile } from '../../lib/catalog-import.js';

const EMPTY_DRAFT={nameEn:'',nameAr:'',benefitEn:'',benefitAr:'',descriptionEn:'',descriptionAr:'',category:'',availability:'',priceType:'fixed',priceLabel:'',currency:'OMR',unit:''};

/**
 * Website import, price-list upload and the full services-and-prices catalog.
 * Advanced setup, so it lives in the dashboard's Business tab rather than in
 * onboarding. `request` posts to the customer surface; `act` runs one action
 * at a time and reports errors.
 */
export function CatalogManager({ lang, request, act, busy, onError, explain, websiteImportAvailable, savedToAccount }) {
  const ar = lang === 'ar';
  const tr = (en, arabic) => ar ? arabic : en;
  const [websiteUrl, setWebsiteUrl] = useState(''), [imported, setImported] = useState(null);
  const [importingFile,setImportingFile]=useState(false);
  const [catalogTab,setCatalogTab]=useState('services'),[catalog,setCatalog]=useState([]),[catalogCursor,setCatalogCursor]=useState(null),[selectedCatalogKey,setSelectedCatalogKey]=useState('');
  const [catalogDraft,setCatalogDraft]=useState(EMPTY_DRAFT);
  async function loadCatalog(cursor=0){const r=await request({action:'catalog_list',cursor,limit:50});setCatalog(current=>cursor?[...current,...(r.catalog.entries||[])]:r.catalog.entries||[]);setCatalogCursor(r.catalog.cursor);}
  async function saveCatalogDraft(source='manual',value=catalogDraft){
    const selected=catalog.find(item=>item.entryKey===(value.entryKey||selectedCatalogKey));
    const addingPrice=catalogTab==='prices'&&selected;
    const nextPrice=value.priceLabel?{type:value.priceType||'fixed',currency:value.currency||'OMR',unit:value.unit||'',label:value.priceLabel}:null;
    const entry={entryKey:value.entryKey||selected?.entryKey||crypto.randomUUID(),kind:value.kind||selected?.kind||'service',nameEn:value.nameEn||selected?.nameEn||'',nameAr:value.nameAr||selected?.nameAr||'',category:value.category||selected?.category||'',benefitEn:value.benefitEn||selected?.benefitEn||'',benefitAr:value.benefitAr||selected?.benefitAr||'',descriptionEn:value.descriptionEn||selected?.descriptionEn||'',descriptionAr:value.descriptionAr||selected?.descriptionAr||'',availability:value.availability||selected?.availability||'',prices:addingPrice?[...(selected.prices||[]),nextPrice].filter(Boolean).slice(0,20):(value.prices||[]).length?value.prices:(nextPrice?[nextPrice]:[]),source:String(source).slice(0,700),confidence:source==='manual'?1:Number(value.confidence||.7),laylaUseEn:value.laylaUseEn||selected?.laylaUseEn||'Answer customer questions about this service and its approved price.',laylaUseAr:value.laylaUseAr||selected?.laylaUseAr||'الإجابة عن أسئلة العملاء حول هذه الخدمة وسعرها المعتمد.',sortOrder:selected?.sortOrder??catalog.length};
    await request({action:'catalog_save',entry});setCatalogDraft({nameEn:'',nameAr:'',benefitEn:'',benefitAr:'',descriptionEn:'',descriptionAr:'',category:'',availability:'',priceType:'fixed',priceLabel:'',currency:'OMR',unit:''});setSelectedCatalogKey('');await loadCatalog();
  }
  async function saveImportedCatalog(){
    const values=(imported?.extracted?.entries||[]).slice(0,Math.max(0,1000-catalog.length)).map((value,index)=>({entryKey:crypto.randomUUID(),kind:value.kind||'service',nameEn:value.nameEn||'',nameAr:value.nameAr||'',category:value.category||'',benefitEn:value.benefitEn||'',benefitAr:value.benefitAr||'',descriptionEn:value.descriptionEn||'',descriptionAr:value.descriptionAr||'',availability:value.availability||'',prices:(value.prices||[]).slice(0,20),source:String(imported.url).slice(0,700),confidence:Number(value.confidence||.7),laylaUseEn:value.laylaUseEn||'Answer customer questions about this service and its approved price.',laylaUseAr:value.laylaUseAr||'الإجابة عن أسئلة العملاء حول هذه الخدمة وسعرها المعتمد.',sortOrder:catalog.length+index}));
    for(let index=0;index<values.length;index+=25)await request({action:'catalog_save_many',entries:values.slice(index,index+25)});
    await loadCatalog();
  }
  // Loads once the setup is saved to an account; loadCatalog only reads props.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{if(savedToAccount)loadCatalog().catch(()=>{});},[savedToAccount]);
  return <>
          {websiteImportAvailable && <details><summary>{tr('Fill this in from your website — the fastest way', 'املأ هذا من موقعك — الطريقة الأسرع')}</summary>
            <label>{tr('Import from your website','استيراد من موقعك')}<input type="url" placeholder="https://example.com/services" maxLength={2000} value={websiteUrl} onChange={e=>setWebsiteUrl(e.target.value)} /></label>
            <button type="button" className="layla-secondary" disabled={busy || !websiteUrl} onClick={()=>act(async()=>{const r=await request({action:'import_website',url:websiteUrl});setImported(r.imported);})}>{tr('Scan relevant pages','فحص الصفحات ذات الصلة')}</button>
            {imported&&/^https:\/\//.test(imported.url)&&<div><p>{tr('Source:','المصدر:')} <a href={imported.url} target="_blank" rel="noopener noreferrer">{imported.url}</a></p><h4>{tr('1. What are they?','١. ما الخدمات أو المنتجات؟')}</h4><p>{imported.extracted?.questions?.whatTheyAre}</p><h4>{tr('2. How do they help customers?','٢. كيف تخدم العملاء؟')}</h4><p>{imported.extracted?.questions?.howTheyHelp||tr('Review the extracted services below.','راجع الخدمات المستخرجة أدناه.')}</p><h4>{tr('3. How will Layla use this?','٣. كيف ستستخدم ليلى هذه المعلومات؟')}</h4><p>{tr('Layla uses approved services, prices and policies to answer accurately without guessing.','تستخدم ليلى الخدمات والأسعار والسياسات المعتمدة للإجابة بدقة دون تخمين.')}</p>{imported.partial&&<p className="layla-notice">{tr('Useful information was extracted; oversized content was skipped.','تم استخراج المعلومات المفيدة وتجاوز المحتوى الكبير.')}</p>}{savedToAccount&&!!imported.extracted?.entries?.length&&<button type="button" className="layla-primary" disabled={busy} onClick={()=>act(saveImportedCatalog)}>{tr('Add all extracted drafts','إضافة كل المسودات المستخرجة')}</button>}{savedToAccount&&imported.extracted?.entries?.map((entry,i)=><button key={i} type="button" className="layla-secondary" onClick={()=>act(()=>saveCatalogDraft(imported.url,{...entry,priceLabel:entry.prices?.[0]?.label,priceType:entry.prices?.[0]?.type,currency:entry.prices?.[0]?.currency,unit:entry.prices?.[0]?.unit}))}>{tr('Add draft:','إضافة مسودة:')} {entry.nameEn||entry.nameAr}</button>)}</div>}
          </details>}
          {savedToAccount&&<details><summary>{tr('Upload a price list or catalog — we read it for you','ارفع قائمة أسعار أو كتالوج — نقرأه عنك')}</summary><p>{tr('PDF, CSV, XLSX, DOCX, TXT, JPG, PNG or WebP. The file is read in your browser and extracted items remain drafts.','PDF أو CSV أو XLSX أو DOCX أو TXT أو JPG أو PNG أو WebP. يُقرأ الملف في متصفحك وتبقى العناصر المستخرجة مسودات.')}</p><input aria-label={tr('Price list or catalog file','ملف قائمة الأسعار أو الكتالوج')} type="file" accept=".pdf,.csv,.xlsx,.docx,.txt,.jpg,.jpeg,.png,.webp" disabled={busy||importingFile} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setImportingFile(true);onError('');try{const parsed=await readCatalogFile(file);setImported({url:file.name,text:parsed.text,partial:parsed.partial,extracted:{questions:{whatTheyAre:parsed.text.slice(0,500),howTheyHelp:'',howLaylaUsesIt:''},entries:parsed.entries}});}catch(error){onError(explain(error.message));}finally{setImportingFile(false);e.target.value='';}}}/>{importingFile&&<p role="status">{tr('Reading catalog…','جارٍ قراءة الكتالوج…')}</p>}{imported&&!/^https:\/\//.test(imported.url)&&<div><p>{tr('Extracted draft items:','العناصر المستخرجة كمسودة:')} {imported.extracted?.entries?.length||0}</p>{!!imported.extracted?.entries?.length&&<button type="button" className="layla-primary" disabled={busy} onClick={()=>act(saveImportedCatalog)}>{tr('Add all extracted drafts','إضافة كل المسودات المستخرجة')}</button>}{imported.extracted?.entries?.map((entry,i)=><button key={i} type="button" className="layla-secondary" onClick={()=>act(()=>saveCatalogDraft(imported.url,{...entry,priceLabel:entry.prices?.[0]?.label,priceType:entry.prices?.[0]?.type,currency:entry.prices?.[0]?.currency,unit:entry.prices?.[0]?.unit}))}>{tr('Add draft:','إضافة مسودة:')} {entry.nameEn||entry.nameAr}</button>)}</div>}</details>}
          {savedToAccount&&<details><summary>{tr('Your full list of services and prices','قائمة خدماتك وأسعارك الكاملة')}</summary><section className="layla-catalog" aria-labelledby="catalog-heading"><h3 id="catalog-heading">{tr('Services & prices','الخدمات والأسعار')}</h3><div className="layla-quick-questions"><button type="button" className={catalogTab==='services'?'layla-primary':'layla-secondary'} onClick={()=>setCatalogTab('services')}>{tr('Services','الخدمات')}</button><button type="button" className={catalogTab==='prices'?'layla-primary':'layla-secondary'} onClick={()=>setCatalogTab('prices')}>{tr('Prices','الأسعار')}</button></div>
            <p>{tr('Add up to 1,000 services or products. Imported information stays a draft until you publish it.','أضف حتى ١٠٠٠ خدمة أو منتج. تبقى المعلومات المستوردة مسودة حتى تنشرها.')}</p>
            {catalogTab==='services'?<><label>{tr('Service name in English','اسم الخدمة بالإنجليزية')}<input maxLength={160} value={catalogDraft.nameEn} onChange={e=>setCatalogDraft({...catalogDraft,nameEn:e.target.value})}/></label><label>{tr('Service name in Arabic','اسم الخدمة بالعربية')}<input dir="rtl" maxLength={160} value={catalogDraft.nameAr} onChange={e=>setCatalogDraft({...catalogDraft,nameAr:e.target.value})}/></label><label>{tr('How does it help customers?','كيف تساعد العملاء؟')}<textarea maxLength={700} value={ar?catalogDraft.benefitAr:catalogDraft.benefitEn} onChange={e=>setCatalogDraft({...catalogDraft,[ar?'benefitAr':'benefitEn']:e.target.value})}/></label><label>{tr('Details Layla may explain','تفاصيل يمكن لليلى شرحها')}<textarea maxLength={700} value={ar?catalogDraft.descriptionAr:catalogDraft.descriptionEn} onChange={e=>setCatalogDraft({...catalogDraft,[ar?'descriptionAr':'descriptionEn']:e.target.value})}/></label></>:<><label>{tr('Choose a service','اختر خدمة')}<select value={selectedCatalogKey} onChange={e=>setSelectedCatalogKey(e.target.value)}><option value="">{tr('Select an existing service','اختر خدمة موجودة')}</option>{catalog.filter(item=>item.source!=='hasib_stock').map(item=><option key={item.entryKey} value={item.entryKey}>{(ar?item.nameAr:item.nameEn)||item.nameEn||item.nameAr}</option>)}</select></label><label>{tr('Price type','نوع السعر')}<select value={catalogDraft.priceType} onChange={e=>setCatalogDraft({...catalogDraft,priceType:e.target.value})}>{[['fixed',tr('Fixed','ثابت')],['from',tr('Starting from','ابتداءً من')],['range',tr('Range','نطاق')],['free',tr('Free','مجاني')],['quote',tr('Quote required','بحسب عرض السعر')],['recurring',tr('Recurring','متكرر')],['unavailable',tr('Not available','غير متاح')]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>{tr('Displayed price','السعر المعروض')}<input maxLength={160} placeholder={tr('Example: From 20 OMR','مثال: ابتداءً من ٢٠ ر.ع.')} value={catalogDraft.priceLabel} onChange={e=>setCatalogDraft({...catalogDraft,priceLabel:e.target.value})}/></label><label>{tr('Currency','العملة')}<select value={catalogDraft.currency} onChange={e=>setCatalogDraft({...catalogDraft,currency:e.target.value})}>{['OMR','AED','SAR','USD'].map(v=><option key={v}>{v}</option>)}</select></label></>}
            <button type="button" className="layla-primary" disabled={busy||(catalogTab==='services'?!(catalogDraft.nameEn.trim()||catalogDraft.nameAr.trim()):!selectedCatalogKey||!catalogDraft.priceLabel.trim())} onClick={()=>act(()=>saveCatalogDraft())}>{catalogTab==='services'?tr('Add service','إضافة خدمة'):tr('Add price','إضافة سعر')}</button>
            {catalog.map(item=><div className="layla-faq" key={item.entryKey}><strong>{(ar?item.nameAr:item.nameEn)||item.nameEn||item.nameAr}</strong><p>{(ar?item.benefitAr:item.benefitEn)||item.descriptionEn||item.descriptionAr}</p>{item.prices?.map((p,i)=><p key={i}>{p.label}</p>)}<small>{item.source==='hasib_stock'?tr('From your stock — edit it in Stock','من مخزونك — عدّله من المخزون'):item.status==='approved'?tr('Approved','معتمد'):tr('Draft','مسودة')}</small>{item.source!=='hasib_stock'&&<button type="button" className="layla-secondary" onClick={()=>act(async()=>{await request({action:'catalog_archive',entryKey:item.entryKey});await loadCatalog();})}>{tr('Archive','أرشفة')}</button>}</div>)}
            {!!catalog.length&&<button type="button" className="layla-secondary" disabled={busy} onClick={()=>act(async()=>{await request({action:'catalog_publish'});await loadCatalog();})}>{tr('Approve and publish catalog','اعتماد ونشر الكتالوج')}</button>}
            {catalogCursor!==null&&<button type="button" className="layla-secondary" disabled={busy} onClick={()=>act(()=>loadCatalog(catalogCursor))}>{tr('Load more services','عرض خدمات إضافية')}</button>}
          </section></details>}
  </>;
}
