// Hasib copy, Arabic and English. Kept apart from the Layla dashboard strings so
// each table stays small; tests/hasib-strings.test.mjs enforces key parity.

const en = {
  notEnoughRecords: 'Not enough records', details: 'Detailed reports', expectedProfit: 'Expected profit on open work', missingCounts: 'Record two physical stock counts to compare actual use.', waste_remake: 'Remade drink',
  orders: 'Orders', stock: 'Stock', newOrder: 'New order', createOrder: 'Create order', orderNumber: 'Order #{number}', noOrders: 'No orders yet. Create one from a chat or here.',
  allOrders: 'All orders', customer: 'Customer', walkIn: 'Walk-in customer', customerName: 'Customer name (optional)', total: 'Total', balance: 'Balance', paid: 'Paid', items: 'Items',
  created: 'Created', channel: 'Channel', status: 'Status', payment: 'Payment', addItem: 'Add product', searchItems: 'Search products or SKU', noItemsFound: 'No matching product.',
  customLine: 'Custom line', lineName: 'Description', qty: 'Qty', unitPrice: 'Unit price', discount: 'Discount', remove: 'Remove', subtotal: 'Subtotal', vat: 'VAT', delivery: 'Delivery',
  deliveryFee: 'Delivery fee', fulfilment: 'Fulfilment', area: 'Area', notes: 'Notes', confirmNow: 'Confirm now (takes stock)', saveOrder: 'Save order', saving: 'Saving…',
  pricesIncludeVat: 'Prices include VAT', fromChat: 'Prefilled from the chat. Check before saving.', unmatched: 'Layla captured “{text}”, which doesn’t match a product. Add it below.',
  onHand: '{count} in stock', shortWarning: 'Some items are short on stock. The order was saved and flagged.', stockShort: 'Short on stock',
  recordPayment: 'Record payment', amount: 'Amount (OMR)', method: 'Method', reference: 'Reference (optional)', refund: 'Refund', payments: 'Payments', noPayments: 'No payments yet.',
  moveTo: 'Move to', history: 'History', lines: 'Lines', close: 'Close', cancel: 'Cancel', save: 'Save', loading: 'Loading…', loadMore: 'Load more', retry: 'Try again',
  products: 'Products', addProduct: 'Add product', editProduct: 'Edit product', noProducts: 'No products yet. Add your first product to start tracking stock.', lowStockOnly: 'Low stock only',
  nameAr: 'Name (Arabic)', nameEn: 'Name (English)', category: 'Category', unit: 'Unit', kind: 'Type', kind_product: 'Product', kind_service: 'Service', trackStock: 'Track stock',
  photo: 'Photo', addPhoto: 'Add photo', changePhoto: 'Change photo', removePhoto: 'Remove photo', uploadingPhoto: 'Uploading…', photoHelp: 'Layla sends this photo when a customer asks about the product. JPG, PNG or WebP.', noPhoto: 'No photo',
  variants: 'Variants', addVariant: 'Add variant', sku: 'SKU', price: 'Price (OMR)', cost: 'Cost (OMR)', reorderPoint: 'Alert at', openingStock: 'Opening stock', archive: 'Archive',
  archiveConfirm: 'Archive {name}? It leaves the list; its orders and stock history stay.', adjustStock: 'Adjust stock', reasonLabel: 'Reason', quantity: 'Quantity', unitCost: 'Unit cost (OMR, optional)',
  move_stock_in: 'Received stock', move_return: 'Customer return', move_adjustment: 'Correction (+/−)', move_damage: 'Damaged or lost', move_sale: 'Sold', move_sale_reversal: 'Sale reversed', move_opening: 'Opening stock',
  lowStock: 'Low', stockValue: 'Stock at cost', ordersSummary: '{count} orders · lifetime {total} · owes {balance}', noOrdersForContact: 'No orders yet.',
  st_pending: 'New', st_confirmed: 'Confirmed', st_ready: 'Ready', st_out_for_delivery: 'Out for delivery', st_failed_delivery: 'Delivery failed', st_delivered: 'Delivered', st_completed: 'Completed', st_cancelled: 'Cancelled', st_returned: 'Returned',
  pay_unpaid: 'Unpaid', pay_partial: 'Part paid', pay_paid: 'Paid', pay_overpaid: 'Overpaid',
  ch_whatsapp: 'WhatsApp', ch_instagram: 'Instagram', ch_walk_in: 'Walk-in', ch_phone: 'Phone', ch_website: 'Website', ch_other: 'Other',
  ful_pickup: 'Pickup', ful_delivery: 'Delivery', ful_in_store: 'In store',
  pm_cash: 'Cash', pm_cod: 'Cash on delivery', pm_card: 'Card', pm_bank_transfer: 'Bank transfer', pm_payment_link: 'Payment link', pm_other: 'Other',
  insights: 'Money', expenses: 'Expenses', period_today: 'Today', period_7d: 'Last 7 days', period_30d: 'Last 30 days', period_month: 'This month', period_prev_month: 'Last month',
  netProfit: 'Recorded profit', netProfitHelp: 'Completed work, after recorded item costs and operating costs; excludes VAT.', sales: 'Sales', grossProfit: 'Gross profit', operatingCosts: 'Operating costs',
  cashIn: 'Money received', owed: 'Customers owe you', owedHelp: 'Unpaid balances on open orders', pendingOrders: 'Not yet confirmed', topProducts: 'Best sellers', revenue: 'Revenue', profit: 'Profit',
  noSales: 'No sales in this period yet.', cashByMethod: 'Cash received by method', costsByCategory: 'Costs by category', stockBought: 'Stock bought {amount} (reaches profit as cost of goods)',
  stockValueTile: 'Stock value at cost', lowTile: 'Low stock', outTile: 'Out of stock', buyers: 'Customers who bought', returning: 'Returning', walkInSales: 'Walk-in sales',
  demandTitle: 'What customers ask Layla for', mostWanted: 'Most wanted', lostSales: 'Asked while out of stock', askedNotBought: 'Asked, didn’t buy', notInCatalog: 'Asked for, not in your products',
  people: 'People', asks: 'Asks', bought: 'Bought', noDemand: 'No product questions in this period yet. When customers ask Layla about a product, it shows here.',
  definitions: 'How these are counted: a sale is a confirmed order that was not cancelled or returned. Revenue and profit exclude VAT. Stock purchases are not operating costs — they reach profit as cost of goods when sold.',
  truncated: 'Only the most recent records in this period were counted.', exportCsv: 'Export CSV',
  addExpense: 'Add expense', noExpenses: 'No expenses in this period.', expenseDate: 'Date paid', vendor: 'Paid to (optional)', vatIncluded: 'VAT included (OMR, optional)', voidExpense: 'Void',
  voidConfirm: 'Void this expense? It stays in the history, marked void, and stops counting.', voided: 'Void', expenseTotal: 'Total',
  readyBy: 'Ready by (optional)', depositNow: 'Deposit taken now (OMR, optional)', depositMethod: 'Deposit method', copyReceipt: 'Copy receipt', copied: 'Copied', exchange: 'Exchange',
  exchangeHelp: 'Marks this order returned (stock comes back) and starts a new order for the same customer.', due: 'Due {date}', depositFailed: 'The order was saved, but the deposit wasn’t recorded. Record it from the order.',
  amountCol: 'Amount', paidTo: 'Paid to', outOfStock: 'Out of stock',
  flag_options_unconfirmed: 'Size or options not confirmed with the customer', flag_out_of_stock: 'Not enough in stock — reply to the customer or receive stock', flag_change_requested: 'The customer asked to change this order', flag_needs_review: 'Layla could not confirm this one — please check it',
  waitingForYou: 'Waiting for you (from Layla)', fromLayla: 'From Layla', laylaWaitingTile: 'Layla orders waiting', laylaOverdue: '{count} waiting more than a day', ordersInChat: 'Orders in this chat', pickToConfirm: 'Choose the IMEI for each unit to confirm this order.', confirmOrder: 'Confirm with these units',
  changeIndustry: 'Change industry', currentIndustry: 'Current', comingSoon: 'Coming soon', nextIndustries: 'Coming next — we add industries one at a time', service: 'Service',
  serialized: 'Track IMEI / serial per unit', warrantyMonths: 'Warranty (months)', warrantyBy: 'Warranty from', wb_store: 'Our store', wb_agent: 'Official agent', wb_none: 'No warranty',
  imei: 'IMEI / serial', imeis: 'IMEIs / serials', imeiHelp: 'One per line. Scanning with a barcode reader works.', imeiCount: '{count} entered', pickImeis: 'Choose the units sold',
  noImeis: 'No units in stock for this product.', imeiNeeded: 'Choose {count} IMEI(s) for {name}', unitsInStock: '{count} units', serializedChip: 'IMEI',
  warrantyLookup: 'Warranty lookup', lookup: 'Look up', lookupPlaceholder: 'Scan or type an IMEI', notFound: 'This IMEI is not in your records.',
  soldOn: 'Sold {date}', warrantyActive: 'Under warranty until {date} ({days} days left)', warrantyExpired: 'Warranty ended {date}', noWarranty: 'No warranty recorded',
  st_serial_in_stock: 'In stock', st_serial_reserved: 'Reserved', st_serial_sold: 'Sold', st_serial_written_off: 'Written off', src_purchase: 'Bought from supplier', src_trade_in: 'Trade-in',
  tradeIn: 'Trade-in', tradeInTitle: 'Buy a used device', tradeInProduct: 'Used product', tradeInCost: 'Price paid (OMR)', seller: 'Seller name (optional)', condition: 'Condition notes',
  tradeInDone: 'Trade-in #{number} saved. The device is now in stock.', tradeInsTile: 'Trade-ins bought', noUsedProducts: 'Add a product with IMEI tracking first (for example “iPhone 13 — used”).',
  repairs: 'Repairs', newRepair: 'New repair', noRepairs: 'No repair tickets yet.', device: 'Device', fault: 'Fault', accessoriesLeft: 'Left with device (optional)', quote: 'Quote (OMR)',
  dueDate: 'Promised by (optional)', repairNumber: 'Repair #{number}', underWarranty: 'Under warranty', warrantyByStore: 'Store warranty — labour not charged', warrantyByAgent: 'Official agent warranty',
  labour: 'Labour (OMR)', parts: 'Parts from stock', addPart: 'Add part', saveQuote: 'Save quote and parts', repairLocked: 'Quote and parts are fixed once the device is ready.',
  openRepairs: 'In the workshop', readyRepairs: 'Ready to collect', countLabel: 'Count: {count}', allRepairs: 'All repairs', labourLine: 'Repair labour — {device}',
  rs_received: 'Received', rs_diagnosing: 'Diagnosing', rs_waiting_parts: 'Waiting for parts', rs_repairing: 'Repairing', rs_ready: 'Ready', rs_collected: 'Collected', rs_cancelled: 'Cancelled',
  industryTitle: 'Set up orders and stock', industryIntro: 'Hasib is being released one industry at a time. Choose the industry that fits your shop to open orders, stock, expenses and insights.', industryLayla: 'This only changes Hasib. Layla keeps her current business details and replies.', chooseIndustry: 'Use {name}', industry: 'Industry: {name}', choosing: 'Setting up…',
  currency: 'OMR', invalidAmount: 'Enter an amount like 12.500',
  // Import from a file
  importStock: 'Import from a file', importTitle: 'Add products from a file', importIntro: 'Use the file you already keep: Excel, CSV, PDF, Word, or a photo of your price list. You check everything before it is saved.',
  chooseStockFile: 'Choose file', downloadExample: 'Download an example file', readingFile: 'Reading your file…', readingPhotoSlow: 'Reading a photo can take up to a minute.',
  matchColumns: 'Which column is which?', moreColumns: 'More columns', noColumn: 'Not in the file',
  col_name: 'Product name', col_nameAr: 'Name (Arabic)', col_nameEn: 'Name (English)', col_price: 'Price', col_quantity: 'Quantity in stock', col_cost: 'Cost', col_sku: 'SKU / barcode', col_category: 'Category', col_reorderPoint: 'Alert at', col_serial: 'IMEI / serial',
  importSummary: 'Products: {products} · Options: {variants} · In stock: {units}', importIssues: 'Lines to fix — skipped for now ({count}):', importLine: 'Line {line}: {reason}', importShowing: 'Showing the first {shown} of {total}.',
  addProductsNow: 'Add products ({count})', chooseAnother: 'Choose another file', savingProducts: 'Saving {done} of {total}…', addingPhotos: 'Adding photos {done} of {total}…',
  importDone: 'Done: {created} new, {updated} updated.', importFailedList: 'Not saved ({count}):', photosAdded: 'Photos added: {count}.', photosFromFile: 'Photos in the file: {count}',
  bulkPhotos: 'Add photos by file name', bulkPhotosHelp: 'Name each picture with the product’s SKU or name, for example AB-1.jpg or Black abaya.jpg.', photosUnmatched: 'No product matched: {names}', done: 'Done',
  issue_name_missing: 'the name is missing', issue_price_missing: 'the price is missing', issue_price_invalid: 'the price isn’t a number', issue_cost_invalid: 'the cost isn’t a number', issue_quantity_invalid: 'the quantity isn’t a whole number',
  issue_alert_invalid: 'the alert level isn’t a whole number', issue_serial_invalid: 'the IMEI / serial looks wrong', issue_duplicate_sku: 'this SKU belongs to another product', issue_duplicate_serial: 'this IMEI is listed twice',
  // Today
  todayTitle: 'Today', needsYou: 'Needs you', allClear: 'No actions waiting in the recorded activity.', ordersWaitingLine: 'Orders waiting for you: {count}', chatsHandedLine: 'Chats handed to you: {count}',
  restaurantControls: 'Restaurant controls', cafeControls: 'Café controls', bakeryControls: 'Bakery controls', foodCost: 'Food cost', productCost: 'Product cost', laborCost: 'Labor cost', primeCost: 'Prime cost', wasteCost: 'Waste cost', stockVariance: 'Stock that doesn’t match', menuPerformance: 'Menu performance', contribution: 'Left after item costs', actualUsage: 'Actual use compared with recipes',
  recipe: 'Recipe', recipes: 'Recipes', saveRecipe: 'Save recipe', menuItem: 'Menu item', ingredient: 'Ingredient', ingredients: 'Ingredients', yieldQty: 'Yield portions', addIngredient: 'Add ingredient', removeIngredient: 'Remove ingredient', noRecipes: 'No recipes yet. Add recipes to calculate food cost.',
  receiveStock: 'Receive stock', receivedFrom: 'Supplier', invoiceNumber: 'Invoice number', receivedOn: 'Received on', useBy: 'Use by', producedOn: 'Produced on', recordWaste: 'Record waste', wasteReason: 'Waste reason', countedQty: 'Counted quantity', recordCount: 'Record count', countStock: 'Count stock', prepBatch: 'Prep batch', productionBatch: 'Production batch', productionOutput: 'Finished product', shelfLife: 'Shelf life', expiringStock: 'Expiring stock', expiredStock: 'Expired stock', noExpiringStock: 'No dated stock needs attention.',
  waste_spoilage: 'Spoilage', waste_prep_trim: 'Prep trim', waste_overproduction: 'Overproduction', waste_unsold: 'Unsold', waste_expired: 'Expired', waste_failed_batch: 'Failed batch', waste_damaged: 'Damaged', waste_other: 'Other', restaurantSummary: 'Restaurant summary', cafeSummary: 'Café summary', bakerySummary: 'Bakery summary', channelPerformance: 'Channel performance',
  lowStockLine: 'Running low or out of stock: {count}', repairsReadyLine: 'Repairs ready to collect: {count}', seeAll: 'See all', openChats: 'Open chats', openStock: 'Open stock', openService: 'Open service',
  laylaToday: 'Layla today', laylaReplies: 'Replies sent', laylaConfirmed: 'Orders she confirmed', laylaQuestions: 'Product questions',
  moneyTitle: 'Money', moneyToday: 'Money in today', moneyMonth: 'Money in this month', owedToYou: 'Customers owe you',
  help_moneyToday: 'Payments you recorded today, in cash, card or transfer.', help_moneyMonth: 'All payments recorded since the 1st of this month.', help_owedToYou: 'What customers still have to pay on orders that are not finished.',
  help_laylaReplies: 'Messages Layla wrote to customers today.', help_laylaConfirmed: 'Orders Layla checked against your stock and confirmed by herself today.', help_laylaQuestions: 'Times a customer asked about one of your products today.',
  setupTitle: 'Finish setting up', setupProgress: '{done} of {total} done', setup_whatsapp: 'Connect WhatsApp', setup_industry: 'Choose your type of shop', setup_products: 'Add your products', setup_photos: 'Add product photos', setup_services: 'Add your services',
  moreDetails: 'More details', fewerDetails: 'Fewer details', moreDetailsHelp: 'Cost, low-stock alert and SKU are under “More details”.',
  period: 'Period', keepOrder: 'Keep it', actionFailed: 'That didn’t save. Check your connection and try again.',
  cancelConfirm: 'Cancel order {number}? Any stock it took goes back on the shelf. Payments stay recorded; refund them separately if needed.', returnConfirm: 'Mark order {number} as returned? Its pieces go back into stock. Payments stay recorded; refund them separately if needed.',
  exchangeReturnFailed: 'The new order is saved, but the original couldn’t be marked returned. Open it and mark it returned.',
  importStopped: '{count} products were not saved. Import the same file again: products already saved are updated, not duplicated.',
  prTitle: 'Customers waiting for a product', prRecord: 'Record missing size or colour', prRecordTitle: 'Record a product request', prExactVariant: 'Exact size and colour', prEmpty: 'No customer is waiting for a size or colour right now.',
  prBackInStock: 'Back in stock — contact this customer.', prMarkFilled: 'Mark filled', prFillHelp: 'Choose the order where {name} bought this exact size and colour.', prNoOrders: 'This customer has no confirmed order yet. Create the order first, then mark the request filled.',
  prOrderWithVariant: 'Order with this exact size and colour', prCancel: 'Cancel request', prCancelConfirm: 'Cancel the request for {name}? It leaves the waiting list.', prMore: 'Showing the 50 most recent requests.', prProductGone: 'Archived product',
  fuTitle: 'Follow-ups', fuAdd: 'Add follow-up', fuEmpty: 'No follow-ups due. Add one to remember to get back to a customer.', fuDone: 'Mark done', fuDueNow: 'Due', fuMore: 'Showing the next 50 follow-ups.',
  fuLinked: 'Linked record (optional)', fuChooseRecord: 'Choose record', fuReason: 'Reason', fuDue: 'Due date', fuInvalidDate: 'Enter a valid date and time.',
  fuLink_order: 'Order', fuLink_booking: 'Booking', fuLink_membership: 'Membership', fuLink_job: 'Job', fuLink_property: 'Property',
  importSerialNotes: 'IMEI notes on {count} products:', importSerialsSkipped: '{count} IMEIs skipped: already on record, or for an option not in Stock.',
  checkWarranty: 'Check warranty', serviceHelp: 'Repairs, warranty and trade-ins in one service desk.', serviceActions: 'Service actions', noRepairsHelp: 'Create a repair ticket, check a warranty, or record a trade-in.',
  approvedChip: 'Customer approved', awaitingApprovalChip: 'Awaiting customer approval', searchParts: 'Search parts in stock', quoteResetsApproval: 'Saving a changed quote asks the customer to approve again.',
  approvedQuote: 'Customer approved this quote', noApproval: 'No approval recorded', approvalHelp: 'Record the customer’s approval of this quote. Changing the quote or parts needs a new approval.',
  approvedByLabel: 'Name of the customer who approved', recordApproval: 'Record customer approval', approvalFirst: 'Record the customer’s approval of the quote before starting the repair.',
  repairCancelConfirm: 'Cancel this repair? Its parts go back into stock. {paid} already paid stays recorded; a manager can refund it.', repairCollectConfirm: 'The customer still owes {balance}. Hand the device over anyway? You can take the payment later.',
  daysHeldBeforeSale: 'Days held before sale', daysInStockLabel: 'Days in stock', daysInStockShort: '{count} days in stock', writeOffConfirm: 'Write off {count} unit(s)? They leave stock for good and the loss is recorded.', serialsLoadFailed: 'The units couldn’t load.',
  imeiReceiveHint: 'IMEI products start at zero: receive units with their IMEIs through Adjust stock.', repairOrderHelp: 'This order belongs to a repair. Change its status from the repair ticket in Service.',
  teamTitle: 'Team', teamLimit: 'You and up to {limit} employees. Employees sell, take payments and manage stock; money, settings and the team stay with you.', teamInvite: 'Invite employee', teamInviteHelp: 'They sign in with this email and a code we send them. They never see your costs, profit or cash totals.', teamEmail: 'Employee email', teamSendInvite: 'Send invitation', teamInviteSent: 'Invitation sent to {email}.', teamInviteNotSent: 'Invitation saved, but the email didn’t send. Use Resend in a minute.', teamResend: 'Resend', teamRevoke: 'Remove access', teamRevokeConfirm: 'Remove {email} from your team? They are signed out at once and can no longer open your dashboard.', teamEmpty: 'No employees yet', teamEmptyHelp: 'Invite up to five people to take orders and manage stock with you.', teamStatus_pending: 'Invitation sent', teamStatus_active: 'Active', teamStatus_revoked: 'Access removed',
  setupDone: 'Done', setupTodo: 'To do', setupStart: 'Start', onHandShort: '{count} left',
  // Clinics (dental): Today
  requestsLine: 'Asked for a treatment, no visit recorded yet: {count}', unpaidLine: 'Visits with money still owed: {count}', openVisits: 'Open visits', openSupplies: 'Open supplies',
  openChat: 'Open chat', recordVisit: 'Record visit', receptionToday: 'Layla at reception today', serviceQuestions: 'Service questions', priceQuestions: 'Price questions',
  appointmentRequests: 'Appointment requests', handoffs: 'Handed to your team', revenueToday: 'Recorded revenue today',
  help_serviceQuestions: 'Messages today asking what the clinic offers.', help_priceQuestions: 'Messages today asking what a treatment costs.',
  help_appointmentRequests: 'Patients who asked for an appointment today. Layla doesn’t book, so answer them from Chats.', help_handoffs: 'Times Layla passed a conversation to your team today.',
  help_revenueToday: 'Visits recorded today, before VAT. Payments are counted separately.', visitsToday: '{count} visits recorded',
  setup_laylaSector: 'Set Layla’s business type to Dental clinics', setup_treatments: 'Add your treatments and prices', setup_supplies: 'Add the supplies you keep count of',
  // Settings → Accounts and VAT
  accountsTitle: 'Accounts and VAT', accountsIntro: 'How Hasib counts your money. Changes apply to new records; saved ones keep the VAT they were recorded with.',
  vatRegistered: 'VAT registered', vatRate: 'VAT rate (%)', vatin: 'VAT number (optional)', saveSettings: 'Save settings', settingsSaved: 'Saved.',
  businessTimezone: 'Business time zone', timezoneHelp: 'Today, periods and dates follow this time zone.', expenseCategoriesTitle: 'Expense categories', expenseCategoriesHelp: 'These come with your industry.',
};
const ar = {
  notEnoughRecords: 'لا توجد سجلات كافية', details: 'التقارير التفصيلية', expectedProfit: 'الربح المتوقع للأعمال المفتوحة', missingCounts: 'سجّل جردين فعليين للمخزون لمقارنة الاستخدام الفعلي.', waste_remake: 'إعادة تحضير مشروب',
  orders: 'الطلبات', stock: 'المخزون', newOrder: 'طلب جديد', createOrder: 'إنشاء طلب', orderNumber: 'طلب رقم {number}', noOrders: 'لا توجد طلبات بعد. أنشئ طلباً من محادثة أو من هنا.',
  allOrders: 'كل الطلبات', customer: 'العميل', walkIn: 'عميل حضوري', customerName: 'اسم العميل (اختياري)', total: 'الإجمالي', balance: 'المتبقي', paid: 'المدفوع', items: 'الأصناف',
  created: 'التاريخ', channel: 'القناة', status: 'الحالة', payment: 'الدفع', addItem: 'إضافة منتج', searchItems: 'ابحث عن منتج أو رمز SKU', noItemsFound: 'لا يوجد منتج مطابق.',
  customLine: 'بند مخصص', lineName: 'الوصف', qty: 'الكمية', unitPrice: 'سعر الوحدة', discount: 'الخصم', remove: 'حذف', subtotal: 'المجموع الفرعي', vat: 'ضريبة القيمة المضافة', delivery: 'التوصيل',
  deliveryFee: 'رسوم التوصيل', fulfilment: 'طريقة التسليم', area: 'المنطقة', notes: 'ملاحظات', confirmNow: 'تأكيد الآن (يخصم من المخزون)', saveOrder: 'حفظ الطلب', saving: 'جارٍ الحفظ…',
  pricesIncludeVat: 'الأسعار شاملة الضريبة', fromChat: 'تمت التعبئة من المحادثة. راجعها قبل الحفظ.', unmatched: 'التقطت ليلى «{text}» ولا يطابق أي منتج. أضفه بالأسفل.',
  onHand: 'المتوفر {count}', shortWarning: 'بعض الأصناف غير متوفرة بالكمية الكافية. حُفظ الطلب مع تنبيه.', stockShort: 'نقص في المخزون',
  recordPayment: 'تسجيل دفعة', amount: 'المبلغ (ر.ع.)', method: 'طريقة الدفع', reference: 'المرجع (اختياري)', refund: 'استرداد', payments: 'الدفعات', noPayments: 'لا توجد دفعات بعد.',
  moveTo: 'نقل إلى', history: 'السجل', lines: 'البنود', close: 'إغلاق', cancel: 'إلغاء', save: 'حفظ', loading: 'جارٍ التحميل…', loadMore: 'عرض المزيد', retry: 'حاول مجدداً',
  products: 'المنتجات', addProduct: 'إضافة منتج', editProduct: 'تعديل المنتج', noProducts: 'لا توجد منتجات بعد. أضف أول منتج لبدء متابعة المخزون.', lowStockOnly: 'المخزون المنخفض فقط',
  nameAr: 'الاسم (عربي)', nameEn: 'الاسم (إنجليزي)', category: 'الفئة', unit: 'الوحدة', kind: 'النوع', kind_product: 'منتج', kind_service: 'خدمة', trackStock: 'متابعة المخزون',
  photo: 'الصورة', addPhoto: 'إضافة صورة', changePhoto: 'تغيير الصورة', removePhoto: 'حذف الصورة', uploadingPhoto: 'جارٍ الرفع…', photoHelp: 'ترسل ليلى هذه الصورة عندما يسأل عميل عن المنتج. بصيغة JPG أو PNG أو WebP.', noPhoto: 'لا توجد صورة',
  variants: 'الخيارات', addVariant: 'إضافة خيار', sku: 'رمز SKU', price: 'السعر (ر.ع.)', cost: 'التكلفة (ر.ع.)', reorderPoint: 'تنبيه عند', openingStock: 'الرصيد الافتتاحي', archive: 'أرشفة',
  archiveConfirm: 'أرشفة {name}؟ سيختفي من القائمة، وتبقى طلباته وسجل مخزونه.', adjustStock: 'تعديل المخزون', reasonLabel: 'السبب', quantity: 'الكمية', unitCost: 'تكلفة الوحدة (ر.ع.، اختياري)',
  move_stock_in: 'استلام بضاعة', move_return: 'مرتجع من عميل', move_adjustment: 'تصحيح (+/−)', move_damage: 'تالف أو مفقود', move_sale: 'مبيع', move_sale_reversal: 'إلغاء بيع', move_opening: 'رصيد افتتاحي',
  lowStock: 'منخفض', stockValue: 'قيمة المخزون بالتكلفة', ordersSummary: '{count} طلبات · الإجمالي {total} · المتبقي {balance}', noOrdersForContact: 'لا توجد طلبات بعد.',
  st_pending: 'جديد', st_confirmed: 'مؤكد', st_ready: 'جاهز', st_out_for_delivery: 'قيد التوصيل', st_failed_delivery: 'تعذّر التوصيل', st_delivered: 'تم التوصيل', st_completed: 'مكتمل', st_cancelled: 'ملغى', st_returned: 'مرتجع',
  pay_unpaid: 'غير مدفوع', pay_partial: 'مدفوع جزئياً', pay_paid: 'مدفوع', pay_overpaid: 'مدفوع بالزيادة',
  ch_whatsapp: 'واتساب', ch_instagram: 'إنستغرام', ch_walk_in: 'حضوري', ch_phone: 'هاتف', ch_website: 'الموقع', ch_other: 'أخرى',
  ful_pickup: 'استلام', ful_delivery: 'توصيل', ful_in_store: 'في المحل',
  pm_cash: 'نقداً', pm_cod: 'الدفع عند الاستلام', pm_card: 'بطاقة', pm_bank_transfer: 'تحويل بنكي', pm_payment_link: 'رابط دفع', pm_other: 'أخرى',
  insights: 'التقارير', expenses: 'المصروفات', period_today: 'اليوم', period_7d: 'آخر 7 أيام', period_30d: 'آخر 30 يوماً', period_month: 'هذا الشهر', period_prev_month: 'الشهر الماضي',
  netProfit: 'الربح المسجل', netProfitHelp: 'الأعمال المكتملة بعد تكلفة الأصناف والمصروفات المسجلة، بدون ضريبة القيمة المضافة.', sales: 'المبيعات', grossProfit: 'إجمالي الربح', operatingCosts: 'المصروفات التشغيلية',
  cashIn: 'المبالغ المستلمة', owed: 'مبالغ يدين بها العملاء', owedHelp: 'المبالغ غير المدفوعة على الطلبات المفتوحة', pendingOrders: 'غير مؤكدة بعد', topProducts: 'الأكثر مبيعاً', revenue: 'الإيراد', profit: 'الربح',
  noSales: 'لا توجد مبيعات في هذه الفترة بعد.', cashByMethod: 'المبالغ المستلمة حسب الطريقة', costsByCategory: 'المصروفات حسب الفئة', stockBought: 'مشتريات بضاعة {amount} (تدخل الربح كتكلفة بضاعة عند البيع)',
  stockValueTile: 'قيمة المخزون بالتكلفة', lowTile: 'مخزون منخفض', outTile: 'نفد من المخزون', buyers: 'عملاء اشتروا', returning: 'عائدون', walkInSales: 'مبيعات حضورية',
  demandTitle: 'ما يسأل عنه العملاء ليلى', mostWanted: 'الأكثر طلباً', lostSales: 'سُئل عنه وهو غير متوفر', askedNotBought: 'سألوا ولم يشتروا', notInCatalog: 'طُلب وليس ضمن منتجاتك',
  people: 'الأشخاص', asks: 'الأسئلة', bought: 'اشتروا', noDemand: 'لا توجد أسئلة عن منتجات في هذه الفترة بعد. عندما يسأل العملاء ليلى عن منتج سيظهر هنا.',
  definitions: 'طريقة الحساب: البيع هو طلب مؤكد لم يُلغَ ولم يُرجع. الإيراد والربح دون ضريبة القيمة المضافة. مشتريات البضاعة ليست مصروفات تشغيلية، بل تدخل الربح كتكلفة بضاعة عند البيع.',
  truncated: 'احتُسبت أحدث السجلات فقط في هذه الفترة.', exportCsv: 'تصدير CSV',
  addExpense: 'إضافة مصروف', noExpenses: 'لا توجد مصروفات في هذه الفترة.', expenseDate: 'تاريخ الدفع', vendor: 'المدفوع له (اختياري)', vatIncluded: 'الضريبة المشمولة (ر.ع.، اختياري)', voidExpense: 'إلغاء',
  voidConfirm: 'إلغاء هذا المصروف؟ سيبقى في السجل بعلامة «ملغى» ولن يُحتسب.', voided: 'ملغى', expenseTotal: 'الإجمالي',
  readyBy: 'جاهز بتاريخ (اختياري)', depositNow: 'عربون مستلم الآن (ر.ع.، اختياري)', depositMethod: 'طريقة دفع العربون', copyReceipt: 'نسخ الإيصال', copied: 'تم النسخ', exchange: 'استبدال',
  exchangeHelp: 'يسجّل هذا الطلب كمرتجع (يعود المخزون) ويبدأ طلباً جديداً للعميل نفسه.', due: 'موعده {date}', depositFailed: 'حُفظ الطلب لكن لم يُسجَّل العربون. سجّله من صفحة الطلب.',
  amountCol: 'المبلغ', paidTo: 'المدفوع له', outOfStock: 'نفد',
  flag_options_unconfirmed: 'لم يُؤكَّد المقاس أو الخيار مع العميل', flag_out_of_stock: 'الكمية غير كافية — رد على العميل أو استلم بضاعة', flag_change_requested: 'طلب العميل تعديل هذا الطلب', flag_needs_review: 'لم تتمكن ليلى من تأكيده — يرجى المراجعة',
  waitingForYou: 'بانتظارك (من ليلى)', fromLayla: 'من ليلى', laylaWaitingTile: 'طلبات ليلى المنتظرة', laylaOverdue: '{count} تنتظر أكثر من يوم', ordersInChat: 'طلبات هذه المحادثة', pickToConfirm: 'اختر رقم IMEI لكل وحدة لتأكيد الطلب.', confirmOrder: 'تأكيد بهذه الوحدات',
  changeIndustry: 'تغيير القطاع', currentIndustry: 'الحالي', comingSoon: 'قريباً', nextIndustries: 'القطاعات القادمة — نضيفها واحداً تلو الآخر', service: 'الصيانة',
  serialized: 'تتبّع IMEI / الرقم التسلسلي لكل وحدة', warrantyMonths: 'الضمان (بالأشهر)', warrantyBy: 'جهة الضمان', wb_store: 'متجرنا', wb_agent: 'الوكيل الرسمي', wb_none: 'بدون ضمان',
  imei: 'IMEI / الرقم التسلسلي', imeis: 'أرقام IMEI / التسلسلية', imeiHelp: 'رقم في كل سطر. يمكن استخدام قارئ الباركود.', imeiCount: 'تم إدخال {count}', pickImeis: 'اختر الوحدات المباعة',
  noImeis: 'لا توجد وحدات في المخزون لهذا المنتج.', imeiNeeded: 'اختر {count} من أرقام IMEI لـ {name}', unitsInStock: '{count} وحدات', serializedChip: 'IMEI',
  warrantyLookup: 'البحث عن الضمان', lookup: 'بحث', lookupPlaceholder: 'امسح أو اكتب رقم IMEI', notFound: 'رقم IMEI هذا غير موجود في سجلاتك.',
  soldOn: 'بيع في {date}', warrantyActive: 'ضمن الضمان حتى {date} (متبقٍ {days} يوماً)', warrantyExpired: 'انتهى الضمان في {date}', noWarranty: 'لا يوجد ضمان مسجّل',
  st_serial_in_stock: 'في المخزون', st_serial_reserved: 'محجوز', st_serial_sold: 'مباع', st_serial_written_off: 'مشطوب', src_purchase: 'شراء من المورد', src_trade_in: 'استبدال',
  tradeIn: 'استبدال', tradeInTitle: 'شراء جهاز مستعمل', tradeInProduct: 'المنتج المستعمل', tradeInCost: 'المبلغ المدفوع (ر.ع.)', seller: 'اسم البائع (اختياري)', condition: 'ملاحظات الحالة',
  tradeInDone: 'حُفظ الاستبدال رقم {number}. أصبح الجهاز في المخزون.', tradeInsTile: 'أجهزة مستبدلة', noUsedProducts: 'أضف أولاً منتجاً بتتبّع IMEI (مثل «آيفون 13 — مستعمل»).',
  repairs: 'الصيانة', newRepair: 'تذكرة صيانة جديدة', noRepairs: 'لا توجد تذاكر صيانة بعد.', device: 'الجهاز', fault: 'العطل', accessoriesLeft: 'ما تُرك مع الجهاز (اختياري)', quote: 'التسعيرة (ر.ع.)',
  dueDate: 'موعد التسليم (اختياري)', repairNumber: 'صيانة رقم {number}', underWarranty: 'ضمن الضمان', warrantyByStore: 'ضمان المتجر — لا تُحتسب أجرة', warrantyByAgent: 'ضمان الوكيل الرسمي',
  labour: 'الأجرة (ر.ع.)', parts: 'قطع من المخزون', addPart: 'إضافة قطعة', saveQuote: 'حفظ التسعيرة والقطع', repairLocked: 'تُثبّت التسعيرة والقطع عند جاهزية الجهاز.',
  openRepairs: 'في الورشة', readyRepairs: 'جاهزة للاستلام', countLabel: 'العدد: {count}', allRepairs: 'كل تذاكر الصيانة', labourLine: 'أجرة إصلاح — {device}',
  rs_received: 'مستلم', rs_diagnosing: 'قيد الفحص', rs_waiting_parts: 'بانتظار القطع', rs_repairing: 'قيد الإصلاح', rs_ready: 'جاهز', rs_collected: 'تم الاستلام', rs_cancelled: 'ملغى',
  industryTitle: 'إعداد الطلبات والمخزون', industryIntro: 'نطلق حاسب لقطاع تلو الآخر. اختر القطاع المناسب لمتجرك لفتح الطلبات والمخزون والمصروفات والتقارير.', industryLayla: 'هذا يغيّر حاسب فقط. تحتفظ ليلى ببيانات نشاطك وردودها الحالية.', chooseIndustry: 'استخدام {name}', industry: 'القطاع: {name}', choosing: 'جارٍ الإعداد…',
  currency: 'ر.ع.', invalidAmount: 'أدخل مبلغاً مثل 12.500',
  // Import from a file
  importStock: 'استيراد من ملف', importTitle: 'إضافة المنتجات من ملف', importIntro: 'استخدم الملف الموجود لديك: إكسل أو CSV أو PDF أو وورد أو صورة لقائمة الأسعار. تراجع كل شيء قبل الحفظ.',
  chooseStockFile: 'اختر ملفاً', downloadExample: 'تنزيل ملف مثال', readingFile: 'جارٍ قراءة الملف…', readingPhotoSlow: 'قد تستغرق قراءة الصورة حتى دقيقة.',
  matchColumns: 'ما محتوى كل عمود؟', moreColumns: 'أعمدة أخرى', noColumn: 'غير موجود في الملف',
  col_name: 'اسم المنتج', col_nameAr: 'الاسم (عربي)', col_nameEn: 'الاسم (إنجليزي)', col_price: 'السعر', col_quantity: 'الكمية في المخزون', col_cost: 'التكلفة', col_sku: 'رمز SKU / الباركود', col_category: 'الفئة', col_reorderPoint: 'تنبيه عند', col_serial: 'IMEI / الرقم التسلسلي',
  importSummary: 'المنتجات: {products} · الخيارات: {variants} · في المخزون: {units}', importIssues: 'أسطر تحتاج تصحيحاً — سيتم تخطيها الآن ({count}):', importLine: 'السطر {line}: {reason}', importShowing: 'يظهر أول {shown} من {total}.',
  addProductsNow: 'إضافة المنتجات ({count})', chooseAnother: 'اختيار ملف آخر', savingProducts: 'جارٍ الحفظ: {done} من {total}…', addingPhotos: 'جارٍ إضافة الصور: {done} من {total}…',
  importDone: 'تم: جديد {created}، محدَّث {updated}.', importFailedList: 'لم يُحفظ ({count}):', photosAdded: 'الصور المضافة: {count}.', photosFromFile: 'الصور في الملف: {count}',
  bulkPhotos: 'إضافة صور حسب اسم الملف', bulkPhotosHelp: 'سمِّ كل صورة برمز المنتج أو اسمه، مثل AB-1.jpg أو عباية سوداء.jpg.', photosUnmatched: 'لم تطابق أي منتج: {names}', done: 'تم',
  issue_name_missing: 'الاسم غير موجود', issue_price_missing: 'السعر غير موجود', issue_price_invalid: 'السعر ليس رقماً', issue_cost_invalid: 'التكلفة ليست رقماً', issue_quantity_invalid: 'الكمية ليست رقماً صحيحاً',
  issue_alert_invalid: 'حد التنبيه ليس رقماً صحيحاً', issue_serial_invalid: 'رقم IMEI / التسلسلي غير صحيح', issue_duplicate_sku: 'رمز SKU هذا لمنتج آخر', issue_duplicate_serial: 'رقم IMEI هذا مكرر',
  // Today
  todayTitle: 'اليوم', needsYou: 'بانتظارك', allClear: 'كل شيء تمام — ليلى تتولى كل شيء.', ordersWaitingLine: 'طلبات بانتظارك: {count}', chatsHandedLine: 'محادثات حُوّلت إليك: {count}',
  restaurantControls: 'ضوابط المطعم', cafeControls: 'ضوابط المقهى', bakeryControls: 'ضوابط المخبز', foodCost: 'تكلفة الطعام', productCost: 'تكلفة المنتجات', laborCost: 'تكلفة العمالة', primeCost: 'التكلفة الأساسية', wasteCost: 'تكلفة الهدر', stockVariance: 'مخزون غير مطابق', menuPerformance: 'أداء القائمة', contribution: 'المتبقي بعد تكلفة الأصناف', actualUsage: 'الاستخدام الفعلي مقارنة بالوصفات',
  recipe: 'الوصفة', recipes: 'الوصفات', saveRecipe: 'حفظ الوصفة', menuItem: 'صنف القائمة', ingredient: 'المكوّن', ingredients: 'المكوّنات', yieldQty: 'عدد الحصص', addIngredient: 'إضافة مكوّن', removeIngredient: 'حذف المكوّن', noRecipes: 'لا توجد وصفات بعد. أضف الوصفات لحساب تكلفة الطعام.',
  receiveStock: 'استلام مخزون', receivedFrom: 'المورّد', invoiceNumber: 'رقم الفاتورة', receivedOn: 'تاريخ الاستلام', useBy: 'يُستخدم قبل', producedOn: 'تاريخ الإنتاج', recordWaste: 'تسجيل هدر', wasteReason: 'سبب الهدر', countedQty: 'الكمية المعدودة', recordCount: 'تسجيل الجرد', countStock: 'جرد المخزون', prepBatch: 'دفعة تحضير', productionBatch: 'دفعة إنتاج', productionOutput: 'المنتج النهائي', shelfLife: 'مدة الصلاحية', expiringStock: 'مخزون يقترب انتهاءه', expiredStock: 'مخزون منتهي', noExpiringStock: 'لا يوجد مخزون مؤرخ يحتاج إلى متابعة.',
  waste_spoilage: 'تلف', waste_prep_trim: 'بقايا التحضير', waste_overproduction: 'إنتاج زائد', waste_unsold: 'غير مباع', waste_expired: 'منتهي الصلاحية', waste_failed_batch: 'دفعة فاشلة', waste_damaged: 'تالف', waste_other: 'أخرى', restaurantSummary: 'ملخص المطعم', cafeSummary: 'ملخص المقهى', bakerySummary: 'ملخص المخبز', channelPerformance: 'أداء القنوات',
  lowStockLine: 'منتجات قاربت على النفاد أو نفدت: {count}', repairsReadyLine: 'أجهزة جاهزة للاستلام: {count}', seeAll: 'عرض الكل', openChats: 'فتح المحادثات', openStock: 'فتح المخزون', openService: 'فتح الصيانة',
  laylaToday: 'ليلى اليوم', laylaReplies: 'ردود أرسلتها', laylaConfirmed: 'طلبات أكّدتها', laylaQuestions: 'أسئلة عن المنتجات',
  moneyTitle: 'المال', moneyToday: 'دخل اليوم', moneyMonth: 'دخل هذا الشهر', owedToYou: 'مبالغ لك عند العملاء',
  help_moneyToday: 'المدفوعات التي سجّلتها اليوم نقداً أو بالبطاقة أو بالتحويل.', help_moneyMonth: 'كل المدفوعات المسجلة منذ أول الشهر.', help_owedToYou: 'ما بقي على العملاء دفعه في الطلبات غير المنتهية.',
  help_laylaReplies: 'الرسائل التي كتبتها ليلى للعملاء اليوم.', help_laylaConfirmed: 'طلبات راجعتها ليلى مع مخزونك وأكّدتها بنفسها اليوم.', help_laylaQuestions: 'عدد المرات التي سأل فيها عميل عن أحد منتجاتك اليوم.',
  setupTitle: 'أكمل الإعداد', setupProgress: 'أُنجز {done} من {total}', setup_whatsapp: 'ربط واتساب', setup_industry: 'اختيار نوع متجرك', setup_products: 'إضافة منتجاتك', setup_photos: 'إضافة صور المنتجات', setup_services: 'إضافة خدماتك',
  moreDetails: 'تفاصيل أكثر', fewerDetails: 'تفاصيل أقل', moreDetailsHelp: 'التكلفة وتنبيه نفاد المخزون ورمز SKU ضمن «تفاصيل أكثر».',
  period: 'الفترة', keepOrder: 'إبقاء', actionFailed: 'لم يُحفظ. تحقّق من الاتصال وحاول مرة أخرى.',
  cancelConfirm: 'إلغاء الطلب {number}؟ تعود أي بضاعة خُصمت إلى المخزون. تبقى الدفعات مسجلة، ويمكنك استردادها بشكل منفصل.', returnConfirm: 'تسجيل الطلب {number} كمرتجع؟ تعود قطعه إلى المخزون. تبقى الدفعات مسجلة، ويمكنك استردادها بشكل منفصل.',
  exchangeReturnFailed: 'حُفظ الطلب الجديد، لكن تعذّر تسجيل الطلب الأصلي كمرتجع. افتحه وسجّله كمرتجع.',
  importStopped: 'لم يُحفظ {count} منتجاً. استورد الملف نفسه مرة أخرى: المنتجات المحفوظة تُحدَّث ولا تتكرر.',
  prTitle: 'عملاء ينتظرون منتجاً', prRecord: 'تسجيل مقاس أو لون غير متوفر', prRecordTitle: 'تسجيل طلب منتج', prExactVariant: 'المقاس واللون المحددان', prEmpty: 'لا يوجد عميل ينتظر مقاساً أو لوناً الآن.',
  prBackInStock: 'متوفر الآن — تواصل مع هذا العميل.', prMarkFilled: 'تم توفير الطلب', prFillHelp: 'اختر الطلب الذي اشترى فيه {name} هذا المقاس واللون تحديداً.', prNoOrders: 'لا يوجد لهذا العميل طلب مؤكد بعد. أنشئ الطلب أولاً ثم سجّل توفير الطلب.',
  prOrderWithVariant: 'طلب بنفس المقاس واللون', prCancel: 'إلغاء الطلب', prCancelConfirm: 'إلغاء طلب {name}؟ سيخرج من قائمة الانتظار.', prMore: 'يظهر أحدث 50 طلباً.', prProductGone: 'منتج مؤرشف',
  fuTitle: 'المتابعات', fuAdd: 'إضافة متابعة', fuEmpty: 'لا توجد متابعات مستحقة. أضف متابعة لتتذكر العودة إلى عميل.', fuDone: 'تمت المتابعة', fuDueNow: 'مستحقة', fuMore: 'تظهر أقرب 50 متابعة.',
  fuLinked: 'سجل مرتبط (اختياري)', fuChooseRecord: 'اختر السجل', fuReason: 'السبب', fuDue: 'موعد المتابعة', fuInvalidDate: 'أدخل تاريخاً ووقتاً صالحين.',
  fuLink_order: 'طلب', fuLink_booking: 'حجز', fuLink_membership: 'اشتراك', fuLink_job: 'عمل', fuLink_property: 'عقار',
  importSerialNotes: 'ملاحظات IMEI على {count} منتجات:', importSerialsSkipped: 'تُخطّي {count} من أرقام IMEI: مسجلة سابقاً أو لخيار غير موجود في المخزون.',
  checkWarranty: 'فحص الضمان', serviceHelp: 'الإصلاحات والضمان والاستبدال في مكان واحد.', serviceActions: 'إجراءات الصيانة', noRepairsHelp: 'أنشئ تذكرة صيانة، أو افحص الضمان، أو سجّل جهاز استبدال.',
  approvedChip: 'وافق العميل', awaitingApprovalChip: 'بانتظار موافقة العميل', searchParts: 'ابحث عن قطع في المخزون', quoteResetsApproval: 'حفظ تسعيرة معدّلة يتطلب موافقة العميل من جديد.',
  approvedQuote: 'وافق العميل على هذه التسعيرة', noApproval: 'لا توجد موافقة مسجلة', approvalHelp: 'سجّل موافقة العميل على هذه التسعيرة. تعديل السعر أو القطع يتطلب موافقة جديدة.',
  approvedByLabel: 'اسم العميل الذي وافق', recordApproval: 'تسجيل موافقة العميل', approvalFirst: 'سجّل موافقة العميل على التسعيرة قبل بدء الإصلاح.',
  repairCancelConfirm: 'إلغاء هذا الإصلاح؟ تعود قطعه إلى المخزون. يبقى المدفوع ({paid}) مسجلاً، ويمكن للمدير استرداده.', repairCollectConfirm: 'ما زال على العميل {balance}. تسليم الجهاز رغم ذلك؟ يمكنك تسجيل الدفعة لاحقاً.',
  daysHeldBeforeSale: 'أيام بقاء الجهاز قبل البيع', daysInStockLabel: 'أيام البقاء في المخزون', daysInStockShort: 'منذ {count} يوم في المخزون', writeOffConfirm: 'شطب {count} وحدة؟ تخرج من المخزون نهائياً وتُسجّل الخسارة.', serialsLoadFailed: 'تعذّر تحميل الوحدات.',
  imeiReceiveHint: 'منتجات IMEI تبدأ من صفر: استلم الوحدات بأرقامها من «تعديل المخزون».', repairOrderHelp: 'هذا الطلب تابع لتذكرة صيانة. غيّر حالته من التذكرة في قسم الصيانة.',
  teamTitle: 'الفريق', teamLimit: 'أنت وحتى {limit} موظفين. الموظفون يبيعون ويسجلون الدفعات ويديرون المخزون، وتبقى الأموال والإعدادات والفريق لك.', teamInvite: 'دعوة موظف', teamInviteHelp: 'يسجّل الدخول بهذا البريد ورمز نرسله إليه، ولا يرى تكاليفك أو أرباحك أو مجاميع النقد.', teamEmail: 'بريد الموظف', teamSendInvite: 'إرسال الدعوة', teamInviteSent: 'أُرسلت الدعوة إلى {email}.', teamInviteNotSent: 'حُفظت الدعوة لكن البريد لم يُرسل. استخدم إعادة الإرسال بعد دقيقة.', teamResend: 'إعادة الإرسال', teamRevoke: 'إلغاء الوصول', teamRevokeConfirm: 'إزالة {email} من فريقك؟ سيُسجَّل خروجه فوراً ولن يتمكن من فتح لوحتك.', teamEmpty: 'لا يوجد موظفون بعد', teamEmptyHelp: 'ادعُ حتى خمسة أشخاص لتسجيل الطلبات وإدارة المخزون معك.', teamStatus_pending: 'أُرسلت الدعوة', teamStatus_active: 'نشط', teamStatus_revoked: 'أُلغي الوصول',
  setupDone: 'تم', setupTodo: 'مطلوب', setupStart: 'ابدأ', onHandShort: 'المتبقي {count}',
  requestsLine: 'طلبوا علاجاً ولم تُسجَّل لهم زيارة بعد: {count}', unpaidLine: 'زيارات عليها مبالغ مستحقة: {count}', openVisits: 'افتح الزيارات', openSupplies: 'افتح المستلزمات',
  openChat: 'افتح المحادثة', recordVisit: 'سجّل زيارة', receptionToday: 'ليلى في الاستقبال اليوم', serviceQuestions: 'أسئلة عن الخدمات', priceQuestions: 'أسئلة عن الأسعار',
  appointmentRequests: 'طلبات مواعيد', handoffs: 'حُوّلت إلى فريقك', revenueToday: 'الإيرادات المسجلة اليوم',
  help_serviceQuestions: 'رسائل اليوم تسأل عمّا تقدّمه العيادة.', help_priceQuestions: 'رسائل اليوم تسأل عن تكلفة علاج.',
  help_appointmentRequests: 'مرضى طلبوا موعداً اليوم. ليلى لا تحجز المواعيد، فرُدّ عليهم من المحادثات.', help_handoffs: 'عدد المرات التي حوّلت فيها ليلى محادثة إلى فريقك اليوم.',
  help_revenueToday: 'الزيارات المسجلة اليوم قبل ضريبة القيمة المضافة. تُحتسب المدفوعات بشكل منفصل.', visitsToday: 'الزيارات المسجلة: {count}',
  setup_laylaSector: 'اجعل نوع نشاط ليلى «عيادات الأسنان»', setup_treatments: 'أضف العلاجات وأسعارها', setup_supplies: 'أضف المستلزمات التي تتابع كمياتها',
  accountsTitle: 'الحسابات والضريبة', accountsIntro: 'طريقة احتساب حسيب لأموالك. تسري التغييرات على السجلات الجديدة، وتحتفظ السجلات المحفوظة بالضريبة التي سُجّلت بها.',
  vatRegistered: 'مسجّل في ضريبة القيمة المضافة', vatRate: 'نسبة الضريبة (%)', vatin: 'الرقم الضريبي (اختياري)', saveSettings: 'حفظ الإعدادات', settingsSaved: 'تم الحفظ.',
  businessTimezone: 'المنطقة الزمنية للنشاط', timezoneHelp: 'يعتمد «اليوم» والفترات والتواريخ على هذه المنطقة الزمنية.', expenseCategoriesTitle: 'فئات المصروفات', expenseCategoriesHelp: 'تأتي هذه الفئات مع نوع نشاطك.',
};

// One industry's own words for the same screens. Keys must exist in the base tables;
// tests/hasib-strings.test.mjs checks both languages carry the same overrides.
const PACK_WORDS = {
  dental: {
    en: {
      orders: 'Visits', stock: 'Services', newOrder: 'Record visit', createOrder: 'Record visit', orderNumber: 'Visit #{number}', noOrders: 'No visits recorded yet. Record one from a chat or here.',
      allOrders: 'All visits', customer: 'Patient', walkIn: 'Patient without a chat', customerName: 'Patient name (optional)', items: 'Treatments', addItem: 'Add treatment',
      searchItems: 'Search treatments', noItemsFound: 'No matching treatment.', customLine: 'Other charge', saveOrder: 'Save visit', confirmNow: 'Confirm now',
      unmatched: 'Layla captured “{text}”, which doesn’t match a treatment. Add it below.', ordersSummary: '{count} visits · lifetime {total} · owes {balance}', noOrdersForContact: 'No visits yet.',
      st_pending: 'Not confirmed', st_confirmed: 'Booked', st_completed: 'Done', st_returned: 'Refunded',
      products: 'Supplies', addProduct: 'Add supply', editProduct: 'Edit supply', noProducts: 'No supplies yet. Add the supplies you want to keep count of.',
      topProducts: 'Revenue by service', owedHelp: 'Unpaid balances on open visits', noSales: 'No visits recorded in this period yet.',
      definitions: 'How these are counted: revenue is every confirmed visit that was not cancelled or refunded, without VAT. Payments count when you record them.',
      ordersInChat: 'Visits in this chat', help_owedToYou: 'What patients still have to pay on visits that are not closed.', openStock: 'Open supplies',
      lowStockLine: 'Supplies running low: {count}', buyers: 'Patients seen', walkInSales: 'Visits without a chat', moneyToday: 'Cash received today',
      help_laylaReplies: 'Messages Layla wrote to patients today.', setup_industry: 'Choose your type of business',
      operatingCosts: 'Expenses', netProfitHelp: 'Revenue minus expenses, both without VAT', stockBought: 'Supplies bought {amount}',
      service: 'Service',
    },
    ar: {
      orders: 'الزيارات', stock: 'الخدمات', newOrder: 'سجّل زيارة', createOrder: 'سجّل زيارة', orderNumber: 'زيارة رقم {number}', noOrders: 'لا توجد زيارات مسجلة بعد. سجّل زيارة من محادثة أو من هنا.',
      allOrders: 'كل الزيارات', customer: 'المريض', walkIn: 'مريض دون محادثة', customerName: 'اسم المريض (اختياري)', items: 'العلاجات', addItem: 'أضف علاجاً',
      searchItems: 'ابحث عن علاج', noItemsFound: 'لا يوجد علاج مطابق.', customLine: 'رسوم أخرى', saveOrder: 'حفظ الزيارة', confirmNow: 'تأكيد الآن',
      unmatched: 'سجّلت ليلى «{text}»، ولا يطابق أي علاج. أضفه أدناه.', ordersSummary: 'الزيارات {count} · الإجمالي {total} · المتبقي {balance}', noOrdersForContact: 'لا توجد زيارات بعد.',
      st_pending: 'غير مؤكدة', st_confirmed: 'محجوزة', st_completed: 'تمت', st_returned: 'مستردة',
      products: 'المستلزمات', addProduct: 'أضف مستلزماً', editProduct: 'تعديل المستلزم', noProducts: 'لا توجد مستلزمات بعد. أضف المستلزمات التي تريد متابعة كمياتها.',
      topProducts: 'الإيرادات حسب الخدمة', owedHelp: 'الأرصدة غير المدفوعة على الزيارات المفتوحة', noSales: 'لا توجد زيارات مسجلة في هذه الفترة بعد.',
      definitions: 'طريقة الاحتساب: الإيراد هو كل زيارة مؤكدة لم تُلغَ ولم تُسترد، دون ضريبة القيمة المضافة. تُحتسب المدفوعات عند تسجيلها.',
      ordersInChat: 'الزيارات في هذه المحادثة', help_owedToYou: 'ما يزال على المرضى دفعه عن زيارات غير مغلقة.', openStock: 'افتح المستلزمات',
      lowStockLine: 'مستلزمات قاربت على النفاد: {count}', buyers: 'مرضى زاروا العيادة', walkInSales: 'زيارات دون محادثة', moneyToday: 'المبالغ المستلمة اليوم',
      help_laylaReplies: 'الرسائل التي كتبتها ليلى للمرضى اليوم.', setup_industry: 'اختيار نوع نشاطك',
      operatingCosts: 'المصروفات', netProfitHelp: 'الإيرادات ناقص المصروفات، دون ضريبة القيمة المضافة', stockBought: 'مستلزمات مشتراة {amount}',
      service: 'الخدمة',
    },
  },
};
const reasons = {
  en: { invalid_order: 'Check the details: a date must be a real date, and fields have a length limit.', invalid_settings: 'Check the settings: a VAT rate from 0 to 100% and a VAT number of letters and digits only.',
    insufficient_stock: 'Not enough stock. Switch the stock rule to “warn” or receive stock first.', order_conflict: 'This order changed in another tab. It has been reloaded.',
    invalid_transition: 'That status change isn’t allowed from here.', refund_exceeds_paid: 'A refund can’t be more than what was paid.', order_closed: 'This order is closed. Only refunds are possible.',
    import_file_too_large: 'That file is too big (15 MB at most).', import_file_type: 'That kind of file can’t be read. Use Excel, CSV, PDF, Word or a photo.', import_file_empty: 'No products were found in that file.', invalid_import: 'Those products couldn’t be saved. Check the file and try again.', serial_mismatch: 'This product is already in Stock without IMEI tracking.', item_not_found: 'That product is no longer in Stock.',
    photo_limit: 'You’ve added a lot of photos today. Try again tomorrow.', invalid_photo: 'That photo can’t be used. Choose a JPG, PNG or WebP picture under 5 MB.', photo_type: 'Choose a JPG, PNG or WebP picture.', photo_size: 'That picture is too big. Choose one under 5 MB.', photo_upload_failed: 'The photo didn’t upload. Check your connection and try again.',
    duplicate_sku: 'Another product already uses that SKU.', invalid_item: 'Check the product: a name and a price are needed for each variant.', invalid_order_lines: 'Check the lines: quantities and prices must be valid.', invalid_recipe: 'Choose a menu item, yield and stocked ingredients.', invalid_waste: 'Check the ingredient, quantity and waste reason.', invalid_count: 'Enter a valid counted quantity.', invalid_receipt: 'Check the supplier, date, quantities and unit costs.', invalid_batch: 'Check the prep output and ingredient quantities.',
    variant_not_found: 'That product is no longer available.', hasib_unavailable: 'Orders and stock are not switched on for this account yet.', invalid_amount: 'Enter a valid amount.', invalid_expense: 'Check the expense: category, amount and date are needed, and VAT can’t exceed the amount.', pack_not_live: 'Choose an available industry to use orders and stock.', serials_required: 'Choose the IMEI of each unit sold.', serial_unavailable: 'That IMEI is not in stock for this product.', serials_mismatch: 'The number of IMEIs must match the quantity.', duplicate_serial: 'That IMEI is already in stock.', invalid_serial: 'Check the IMEI: letters and digits only.', use_serial_flow: 'IMEI products change stock by receiving or writing off named units.', serialized_part: 'Parts with IMEIs are sold as their own order, not as repair parts.', repair_locked: 'Quote and parts are fixed once the device is ready.', repair_conflict: 'This repair changed in another tab. It has been reloaded.', invalid_repair: 'Device and fault are needed.', invalid_trade_in: 'Check the trade-in: price and method are needed.', not_serialized: 'Trade-ins need a product with IMEI tracking.', serial_not_found: 'This IMEI is not in your records.' },
  ar: { invalid_order: 'راجع التفاصيل: يجب أن يكون التاريخ صحيحاً، ولكل حقل حد أقصى للطول.', invalid_settings: 'راجع الإعدادات: نسبة ضريبة من 0 إلى 100% ورقم ضريبي من حروف وأرقام فقط.',
    insufficient_stock: 'الكمية غير كافية. غيّر قاعدة المخزون إلى «تنبيه» أو استلم بضاعة أولاً.', order_conflict: 'تغيّر هذا الطلب في نافذة أخرى، وتمت إعادة تحميله.',
    invalid_transition: 'لا يمكن تغيير الحالة بهذا الشكل.', refund_exceeds_paid: 'لا يمكن أن يتجاوز الاسترداد المبلغ المدفوع.', order_closed: 'هذا الطلب مغلق، ويمكن فقط تسجيل استرداد.',
    import_file_too_large: 'الملف كبير جداً (15 ميغابايت كحد أقصى).', import_file_type: 'لا يمكن قراءة هذا النوع من الملفات. استخدم إكسل أو CSV أو PDF أو وورد أو صورة.', import_file_empty: 'لم نجد منتجات في هذا الملف.', invalid_import: 'تعذّر حفظ هذه المنتجات. راجع الملف وحاول مرة أخرى.', serial_mismatch: 'هذا المنتج موجود في المخزون بدون تتبّع IMEI.', item_not_found: 'هذا المنتج لم يعد في المخزون.',
    photo_limit: 'أضفت صوراً كثيرة اليوم. حاول مرة أخرى غداً.', invalid_photo: 'لا يمكن استخدام هذه الصورة. اختر صورة JPG أو PNG أو WebP أصغر من 5 ميغابايت.', photo_type: 'اختر صورة بصيغة JPG أو PNG أو WebP.', photo_size: 'الصورة كبيرة جداً. اختر صورة أصغر من 5 ميغابايت.', photo_upload_failed: 'لم تُرفع الصورة. تحقّق من الاتصال وحاول مرة أخرى.',
    duplicate_sku: 'رمز SKU مستخدم لمنتج آخر.', invalid_item: 'راجع المنتج: يلزم اسم وسعر لكل خيار.', invalid_order_lines: 'راجع البنود: يجب أن تكون الكميات والأسعار صحيحة.', invalid_recipe: 'اختر صنف القائمة وعدد الحصص ومكوّنات مخزّنة.', invalid_waste: 'راجع المكوّن والكمية وسبب الهدر.', invalid_count: 'أدخل كمية جرد صحيحة.', invalid_receipt: 'راجع المورّد والتاريخ والكميات وتكاليف الوحدة.', invalid_batch: 'راجع ناتج التحضير وكميات المكوّنات.',
    variant_not_found: 'هذا المنتج لم يعد متاحاً.', hasib_unavailable: 'الطلبات والمخزون غير مفعّلة لهذا الحساب بعد.', invalid_amount: 'أدخل مبلغاً صحيحاً.', invalid_expense: 'راجع المصروف: يلزم الفئة والمبلغ والتاريخ، ولا يمكن أن تتجاوز الضريبة المبلغ.', pack_not_live: 'اختر قطاعاً متاحاً لاستخدام الطلبات والمخزون.', serials_required: 'اختر رقم IMEI لكل وحدة مباعة.', serial_unavailable: 'رقم IMEI هذا غير متوفر في المخزون لهذا المنتج.', serials_mismatch: 'يجب أن يطابق عدد أرقام IMEI الكمية.', duplicate_serial: 'رقم IMEI هذا موجود في المخزون بالفعل.', invalid_serial: 'راجع رقم IMEI: أحرف وأرقام فقط.', use_serial_flow: 'منتجات IMEI يتغير مخزونها باستلام وحدات محددة أو شطبها.', serialized_part: 'القطع ذات IMEI تُباع بطلب مستقل وليس كقطع صيانة.', repair_locked: 'تُثبّت التسعيرة والقطع عند جاهزية الجهاز.', repair_conflict: 'تغيّرت هذه التذكرة في نافذة أخرى، وتمت إعادة تحميلها.', invalid_repair: 'يلزم ذكر الجهاز والعطل.', invalid_trade_in: 'راجع الاستبدال: يلزم المبلغ وطريقة الدفع.', not_serialized: 'الاستبدال يتطلب منتجاً بتتبّع IMEI.', serial_not_found: 'رقم IMEI هذا غير موجود في سجلاتك.' },
};

// Workflow failures explain what the owner can do next in either language.
const workflowReasons = {
  booking_conflict: ['This booking changed. Reload it before saving again.', 'تغيّر هذا الحجز. أعد تحميله قبل الحفظ.'],
  capacity_exceeded: ['That provider or room is full at this time. Choose another time.', 'مقدم الخدمة أو الغرفة ممتلئ في هذا الوقت. اختر وقتاً آخر.'],
  resource_unavailable: ['The provider or room is unavailable. Choose another resource or time.', 'مقدم الخدمة أو الغرفة غير متاح. اختر مورداً أو وقتاً آخر.'],
  job_conflict: ['This job changed. Reload it before saving again.', 'تغيّر هذا العمل. أعد تحميله قبل الحفظ.'],
  recipe_conflict: ['This recipe changed. Reopen it to review the latest version.', 'تغيّرت هذه الوصفة. أعد فتحها لمراجعة أحدث إصدار.'],
  membership_conflict: ['This membership changed. Reload it before saving again.', 'تغيّر هذا الاشتراك. أعد تحميله قبل الحفظ.'],
  insufficient_credits: ['No prepaid lessons remain. Record a new lesson pack first.', 'لا توجد دروس مدفوعة متبقية. سجّل باقة دروس جديدة أولاً.'],
  exact_variant_required: ['Choose an order containing this exact size and colour.', 'اختر طلباً يحتوي على هذا المقاس واللون تحديداً.'],
  record_waste_in_stock: ['Open Stock, then Record waste. Its cost is counted once there.', 'افتح المخزون ثم تسجيل هدر. تُحتسب تكلفته مرة واحدة هناك.'],
  food_disposition_required: ['Choose whether the returned food is discarded or approved for sale.', 'اختر التخلص من الطعام المرتجع أو تأكيد صلاحيته للبيع.'],
  use_job_status: ['Change this status from its job card. Payments can still be recorded here.', 'غيّر الحالة من بطاقة العمل. يمكنك تسجيل الدفعات هنا.'],
  invalid_unit: ['Choose a compatible unit, such as grams for kilograms or millilitres for litres.', 'اختر وحدة متوافقة، مثل الغرام للكيلوغرام أو الملليلتر للتر.'],
};
for (const [key, [english, arabic]] of Object.entries(workflowReasons)) { reasons.en[key] = english; reasons.ar[key] = arabic; }

// Refusals every catalog shop can meet, with the next step in both languages.
const shopReasons = {
  repair_not_found: ['That repair ticket is no longer available.', 'تذكرة الصيانة هذه لم تعد متاحة.'],
  use_repair_status: ['This order belongs to a repair. Change its status from the repair ticket in Service. Payments can still be recorded here.', 'هذا الطلب تابع لتذكرة صيانة. غيّر حالته من التذكرة في قسم الصيانة، ويمكنك تسجيل الدفعات هنا.'],
  approval_required: ['Record the customer’s approval of the quote before starting the repair.', 'سجّل موافقة العميل على التسعيرة قبل بدء الإصلاح.'],
  serial_sold: ['That IMEI belongs to a unit you sold. If the customer returned it, mark that order returned instead.', 'رقم IMEI هذا لجهاز بعته. إذا أرجعه العميل، سجّل الطلب كمرتجع بدلاً من ذلك.'],
  duplicate_line: ['Put all units of the same product on one line and pick their IMEIs there.', 'ضع كل وحدات المنتج نفسه في بند واحد واختر أرقام IMEI فيه.'],
  serialized_not_editable: ['IMEI units are already picked for this order, so its lines can’t be changed. Cancel it and create a new one.', 'اختيرت أرقام IMEI لهذا الطلب، فلا يمكن تعديل بنوده. ألغِه وأنشئ طلباً جديداً.'],
  module_unavailable: ['That isn’t part of your industry setup.', 'هذه الميزة ليست ضمن إعداد نشاطك.'],
  invalid_request: ['That didn’t go through. Reload the page and try again.', 'لم يتم ذلك. أعد تحميل الصفحة وحاول مرة أخرى.'],
  order_not_found: ['That order is no longer available. It may have been removed or belongs to another customer.', 'هذا الطلب لم يعد متاحاً، ربما حُذف أو يخص عميلاً آخر.'],
  order_locked: ['This order is confirmed, so its lines can’t be changed. Cancel it and create a new one.', 'هذا الطلب مؤكد ولا يمكن تعديل بنوده. ألغِه وأنشئ طلباً جديداً.'],
  invalid_order: ['Check the order: sales channel, delivery method and the extra fields.', 'راجع الطلب: قناة البيع وطريقة التسليم والحقول الإضافية.'],
  invalid_payment_method: ['Choose how the customer paid.', 'اختر طريقة الدفع.'],
  invalid_stock_move: ['Check the quantity: it must match the reason (received adds, damaged removes).', 'راجع الكمية: يجب أن تناسب السبب (الاستلام يضيف والتالف يخصم).'],
  invalid_quantity: ['Enter a quantity between 1 and 10,000.', 'أدخل كمية بين 1 و10,000.'],
  request_conflict: ['This record changed in another tab. It has been reloaded.', 'تغيّر هذا السجل في نافذة أخرى، وتمت إعادة تحميله.'],
  request_not_found: ['That product request is no longer available.', 'طلب المنتج هذا لم يعد متاحاً.'],
  order_not_reversed: ['Cancel or return the order first, then reopen the request.', 'ألغِ الطلب أو سجّل إرجاعه أولاً، ثم أعد فتح الطلب.'],
  followup_conflict: ['This follow-up changed in another tab. It has been reloaded.', 'تغيّرت هذه المتابعة في نافذة أخرى، وتمت إعادة تحميلها.'],
  followup_not_found: ['That follow-up is no longer available.', 'هذه المتابعة لم تعد متاحة.'],
  invalid_followup: ['A follow-up needs a date and a short reason (160 characters at most).', 'المتابعة تحتاج تاريخاً وسبباً قصيراً (160 حرفاً كحد أقصى).'],
  linked_record_not_found: ['Choose an order that belongs to this customer.', 'اختر طلباً يخص هذا العميل.'],
  expense_not_found: ['That expense is no longer available.', 'هذا المصروف لم يعد متاحاً.'],
  invalid_settings: ['Check the setting: enter a whole number of days between 1 and 3650.', 'راجع الإعداد: أدخل عدد أيام صحيحاً بين 1 و3650.'],
  team_limit: ['Your plan includes up to five employees. Revoke one to invite someone new.', 'باقتك تشمل حتى خمسة موظفين. ألغِ وصول أحدهم لدعوة شخص جديد.'],
  member_not_found: ['That employee is no longer on your team.', 'هذا الموظف لم يعد ضمن فريقك.'],
  member_not_pending: ['This person has already accepted, so there is nothing to resend.', 'قبل هذا الشخص الدعوة بالفعل، فلا حاجة لإعادة إرسالها.'],
  employee_already_member: ['That email is already invited to a team.', 'هذا البريد مدعو بالفعل إلى فريق.'],
  employee_owns_workspace: ['That email already runs its own BznsFlow business, so it can’t join as an employee.', 'هذا البريد يدير نشاطاً خاصاً على BznsFlow، فلا يمكن إضافته كموظف.'],
  invalid_email: ['Enter a valid email address.', 'أدخل بريداً إلكترونياً صحيحاً.'],
  industry_profile_required: ['Choose your industry in Business details first.', 'اختر نوع نشاطك من تفاصيل النشاط أولاً.'],
  invite_send_failed: ['The invitation is saved, but the email didn’t send. Use Resend in a minute.', 'حُفظت الدعوة لكن البريد لم يُرسل. استخدم إعادة الإرسال بعد دقيقة.'],
  invalid_cursor: ['The list changed. It has been reloaded from the top.', 'تغيّرت القائمة، وتمت إعادة تحميلها من البداية.'],
  item_archived: ['A product in this order has been archived. Remove it or restore the product before confirming.', 'منتج في هذا الطلب مؤرشف. احذفه أو أعد المنتج قبل التأكيد.'],
  payment_exceeds_balance: ['That’s more than the customer still owes on this order.', 'المبلغ أكبر مما تبقّى على العميل في هذا الطلب.'],
  item_has_stock: ['This product still has pieces in stock. Adjust the stock to zero before changing how it’s tracked.', 'لا تزال لهذا المنتج قطع في المخزون. عدّل المخزون إلى صفر قبل تغيير طريقة تتبّعه.'],
  record_not_found: ['That record is no longer available. Reload the page.', 'هذا السجل لم يعد متاحاً. أعد تحميل الصفحة.'],
  too_many_variants: ['A product can have up to 50 sizes and colours. Add the rest as a new product.', 'يمكن أن يكون للمنتج حتى 50 مقاساً ولوناً. أضف الباقي كمنتج جديد.'],
  preview_forbidden: ['Industry previews are for the BznsFlow team only.', 'معاينة القطاعات متاحة لفريق BznsFlow فقط.'],
  preview_read_only: ['This is a read-only preview. Nothing is saved.', 'هذه معاينة للقراءة فقط، ولا يُحفظ شيء.'],
};
for (const [key, [english, arabic]] of Object.entries(shopReasons)) { reasons.en[key] = english; reasons.ar[key] = arabic; }
// Real Estate refusals (convex/hasib/realEstateState.js).
const realEstateReasons = {
  invalid_stage_transition: ['A deal moves forward one step at a time, or to Lost. It is won only by closing it.', 'تتقدّم الصفقة خطوة بخطوة أو تُسجَّل كخاسرة، ولا تُحتسب رابحة إلا بإغلاقها.'],
  lost_reason_required: ['Say why the deal was lost.', 'اذكر سبب خسارة الصفقة.'],
  qualification_incomplete: ['Add areas, property type, maximum budget, finance, decision maker and timeline first.', 'أضف المناطق ونوع العقار والحد الأعلى للميزانية والتمويل وصاحب القرار والإطار الزمني أولاً.'],
  opportunity_closed: ['This deal is closed and can no longer be edited.', 'هذه الصفقة مغلقة ولا يمكن تعديلها.'],
  opportunity_assigned_elsewhere: ['This customer already has an open deal with another agent.', 'لدى هذا العميل صفقة مفتوحة مع وكيل آخر.'],
  opportunity_not_found: ['That deal is not available to you. Reload the page.', 'هذه الصفقة غير متاحة لك. أعد تحميل الصفحة.'],
  opportunity_conflict: ['Someone changed this deal. It has been reloaded; try again.', 'عدّل شخص آخر هذه الصفقة. أعد المحاولة بعد التحديث.'],
  invalid_opportunity: ['Check the budget and the customer’s requirements.', 'تحقّق من الميزانية ومتطلبات العميل.'],
  invalid_assignment: ['You can assign a deal or listing only to yourself.', 'يمكنك إسناد الصفقة أو العقار إلى نفسك فقط.'],
  invalid_viewing: ['Check the viewing date and time.', 'تحقّق من تاريخ ووقت المعاينة.'],
  invalid_viewing_transition: ['This viewing is already finished.', 'هذه المعاينة منتهية بالفعل.'],
  viewing_outcome_required: ['Write how the viewing went before marking it completed.', 'اكتب نتيجة المعاينة قبل تسجيلها كمكتملة.'],
  viewing_conflict: ['Someone changed this viewing. Try again.', 'عدّل شخص آخر هذه المعاينة. أعد المحاولة.'],
  invalid_offer: ['An offer needs an amount and its terms.', 'يحتاج العرض إلى مبلغ وشروط.'],
  offer_approval_required: ['The manager must approve this offer before it is presented.', 'يجب أن يوافق المدير على العرض قبل تقديمه.'],
  invalid_offer_transition: ['That step isn’t possible for this offer now.', 'لا يمكن تنفيذ هذه الخطوة على العرض الآن.'],
  offer_conflict: ['Someone changed this offer. Try again.', 'عدّل شخص آخر هذا العرض. أعد المحاولة.'],
  invalid_compliance: ['Choose a check and confirm it or mark it not applicable.', 'اختر بنداً وأكّده أو اجعله غير منطبق.'],
  compliance_conflict: ['Someone changed these checks. Try again.', 'عدّل شخص آخر هذه البنود. أعد المحاولة.'],
  compliance_incomplete: ['Confirm all five compliance checks before closing.', 'أكّد بنود الامتثال الخمسة قبل الإغلاق.'],
  accepted_offer_required: ['Close the deal from its accepted offer.', 'أغلق الصفقة من العرض المقبول.'],
  commission_required: ['Enter the agency commission.', 'أدخل عمولة الوكالة.'],
  property_conflict: ['Someone changed this listing. Try again.', 'عدّل شخص آخر هذا الإعلان. أعد المحاولة.'],
  property_not_found: ['That listing is no longer available.', 'هذا الإعلان لم يعد متاحاً.'],
  invalid_property: ['Check the listing’s title, location and price.', 'تحقّق من عنوان الإعلان والموقع والسعر.'],
  draft_conflict: ['Someone changed this message. Try again.', 'عدّل شخص آخر هذه الرسالة. أعد المحاولة.'],
  invalid_draft: ['Write the message text.', 'اكتب نص الرسالة.'],
  match_not_found: ['That match is no longer available.', 'هذه المطابقة لم تعد متاحة.'],
  commission_not_found: ['That commission record is no longer available.', 'سجل العمولة هذا لم يعد متاحاً.'],
  task_not_found: ['That task is already closed.', 'هذه المهمة مغلقة بالفعل.'],
};
for (const [key, [english, arabic]] of Object.entries(realEstateReasons)) { reasons.en[key] = english; reasons.ar[key] = arabic; }

const GROUPED = new Intl.NumberFormat('en-US', { minimumFractionDigits: 3, maximumFractionDigits: 3 });

/** @param {string} lang @param {string} [packId] the Hasib industry, whose own words replace the defaults */
export function createHasibStrings(lang, packId) {
  const isAr = lang === 'ar', words = PACK_WORDS[packId], table = { ...(isAr ? ar : en), ...(words ? words[isAr ? 'ar' : 'en'] : {}) };
  const t = (key, vars = {}) => String(table[key] ?? en[key] ?? key).replace(/\{(\w+)\}/g, (m, name) => (vars[name] ?? m));
  const reason = code => (isAr ? reasons.ar : reasons.en)[code] || null;
  // Display figures are grouped (1,282.000); inputs and exports keep the plain form parseAmount reads.
  const amount = minor => GROUPED.format(minor / 1000);
  const money = minor => `${amount(minor)} ${table.currency}`;
  const name = row => (isAr ? row.nameAr || row.nameEn : row.nameEn || row.nameAr) || '';
  /** An order line's label: repair labour is rendered in the owner's language. */
  const lineName = l => (l.role === 'labour' ? t('labourLine', { device: l.name }) : l.name);
  // Arabic counts agree with the number: طلب واحد، طلبان، 3–10 طلبات، 11+ طلباً.
  const orders = packId === 'dental'
    ? n => isAr ? (n === 1 ? 'زيارة واحدة' : n === 2 ? 'زيارتان' : n >= 3 && n <= 10 ? `${n} زيارات` : `${n} زيارة`) : `${n} ${n === 1 ? 'visit' : 'visits'}`
    : n => isAr ? (n === 1 ? 'طلب واحد' : n === 2 ? 'طلبان' : n >= 3 && n <= 10 ? `${n} طلبات` : `${n} طلباً`) : `${n} ${n === 1 ? 'order' : 'orders'}`;
  return { t, reason, amount, money, name, lineName, orders, lang, ar: isAr, packId: packId || null };
}
export const HASIB_EN_KEYS = Object.keys(en), HASIB_AR_KEYS = Object.keys(ar);
export const HASIB_REASON_KEYS = { en: Object.keys(reasons.en), ar: Object.keys(reasons.ar) };
export const HASIB_PACK_WORD_KEYS = Object.fromEntries(Object.entries(PACK_WORDS).map(([id, w]) => [id, { en: Object.keys(w.en), ar: Object.keys(w.ar) }]));
