import { defineTable } from 'convex/server';
import { v } from 'convex/values';

const versioned = { accountId: v.id('accounts'), requestId: v.string(), version: v.number(), createdAt: v.number(), updatedAt: v.number() };
const availability = v.array(v.object({ startsAt: v.number(), endsAt: v.number() }));

export const automotiveTables = {
  automotiveVehicles: defineTable({ ...versioned, contactId: v.id('blueContacts'), plate: v.string(), vin: v.optional(v.string()), make: v.string(), model: v.string(), year: v.number(), powertrain: v.string(), odometerKm: v.number(), nextServiceAt: v.optional(v.number()) })
    .index('by_account_created', ['accountId', 'createdAt']).index('by_account_request', ['accountId', 'requestId']).index('by_account_plate', ['accountId', 'plate']).index('by_account_vin', ['accountId', 'vin']).index('by_contact', ['contactId']),
  automotiveBays: defineTable({ ...versioned, name: v.string(), availability, active: v.boolean() })
    .index('by_account_created', ['accountId', 'createdAt']).index('by_account_request', ['accountId', 'requestId']),
  automotiveServices: defineTable({ ...versioned, name: v.string(), category: v.string(), durationMinutes: v.number(), standardLaborMinutes: v.number(), priceMinor: v.number(), checklist: v.array(v.string()), active: v.boolean() })
    .index('by_account_created', ['accountId', 'createdAt']).index('by_account_request', ['accountId', 'requestId']),
  automotiveRequests: defineTable({ ...versioned, contactId: v.id('blueContacts'), conversationId: v.optional(v.id('blueConversations')), vehicleId: v.optional(v.id('automotiveVehicles')), serviceId: v.optional(v.id('automotiveServices')), source: v.string(), channel: v.string(), preferredFrom: v.number(), preferredTo: v.number(), assignedAccountId: v.optional(v.id('accounts')), status: v.string(), firstInboundAt: v.number(), firstResponseSubmittedAt: v.optional(v.number()), appointmentId: v.optional(v.id('automotiveAppointments')) })
    .index('by_account_created', ['accountId', 'createdAt']).index('by_account_status', ['accountId', 'status']).index('by_account_request', ['accountId', 'requestId']),
  automotiveAppointments: defineTable({ ...versioned, contactId: v.id('blueContacts'), vehicleId: v.id('automotiveVehicles'), serviceId: v.id('automotiveServices'), bayId: v.id('automotiveBays'), technicianAccountId: v.id('accounts'), startsAt: v.number(), endsAt: v.number(), status: v.string(), confirmedAt: v.optional(v.number()), checkedInAt: v.optional(v.number()), cancelledAt: v.optional(v.number()), missedAt: v.optional(v.number()), cancellationReason: v.optional(v.string()), workOrderId: v.optional(v.id('automotiveWorkOrders')) })
    .index('by_account_start', ['accountId', 'startsAt']).index('by_account_status', ['accountId', 'status']).index('by_account_request', ['accountId', 'requestId']).index('by_bay_start', ['bayId', 'startsAt']).index('by_technician_start', ['technicianAccountId', 'startsAt']).index('by_account_bay_start', ['accountId', 'bayId', 'startsAt']).index('by_account_technician_start', ['accountId', 'technicianAccountId', 'startsAt']),
  automotiveWorkOrders: defineTable({ ...versioned, number: v.number(), contactId: v.id('blueContacts'), vehicleId: v.id('automotiveVehicles'), appointmentId: v.optional(v.id('automotiveAppointments')), serviceId: v.optional(v.id('automotiveServices')), bayId: v.optional(v.id('automotiveBays')), assignedAdvisorAccountId: v.optional(v.id('accounts')), technicianAccountId: v.optional(v.id('accounts')), repeatOfId: v.optional(v.id('automotiveWorkOrders')), concern: v.string(), promisedAt: v.number(), odometerKm: v.number(), status: v.string(), approvedEstimateVersion: v.optional(v.number()), qualityCheckedAt: v.optional(v.number()), qualityCheckedBy: v.optional(v.id('accounts')), orderId: v.optional(v.id('hasibOrders')), checkedInAt: v.optional(v.number()), startedAt: v.optional(v.number()), readyAt: v.optional(v.number()), collectedAt: v.optional(v.number()), closedAt: v.optional(v.number()), warrantyDisposition: v.optional(v.string()) })
    .index('by_account_created', ['accountId', 'createdAt']).index('by_account_status', ['accountId', 'status']).index('by_account_request', ['accountId', 'requestId']).index('by_vehicle_created', ['vehicleId', 'createdAt']).index('by_technician_created', ['technicianAccountId', 'createdAt']).index('by_account_technician_created', ['accountId', 'technicianAccountId', 'createdAt']).index('by_account_promised', ['accountId', 'promisedAt']).index('by_order', ['orderId']),
  automotiveEstimates: defineTable({ ...versioned, workOrderId: v.id('automotiveWorkOrders'), estimateNumber: v.number(), status: v.string(), lines: v.array(v.object({ kind: v.string(), name: v.string(), variantId: v.optional(v.id('hasibVariants')), qty: v.number(), unitPriceMinor: v.number(), standardMinutes: v.optional(v.number()) })), totalMinor: v.number(), standardMinutes: v.number(), issuedAt: v.optional(v.number()), approvedAt: v.optional(v.number()), approvedBy: v.optional(v.string()), evidenceSource: v.optional(v.string()), recordedBy: v.optional(v.id('accounts')) })
    .index('by_account_created', ['accountId', 'createdAt']).index('by_account_status', ['accountId', 'status']).index('by_account_request', ['accountId', 'requestId']).index('by_work_order', ['workOrderId', 'estimateNumber']),
  automotiveInspections: defineTable({ accountId: v.id('accounts'), requestId: v.string(), workOrderId: v.id('automotiveWorkOrders'), items: v.array(v.object({ category: v.string(), condition: v.string(), note: v.optional(v.string()), photoIds: v.optional(v.array(v.id('_storage'))) })), submittedBy: v.id('accounts'), submittedAt: v.number() })
    .index('by_work_order', ['workOrderId']).index('by_account_request', ['accountId', 'requestId']),
  automotiveInspectionPhotos: defineTable({ accountId: v.id('accounts'), inspectionId: v.id('automotiveInspections'), storageId: v.id('_storage'), createdAt: v.number() })
    .index('by_inspection', ['inspectionId']).index('by_storage', ['storageId']),
  automotiveLaborEntries: defineTable({ ...versioned, workOrderId: v.id('automotiveWorkOrders'), technicianAccountId: v.id('accounts'), startedAt: v.number(), stoppedAt: v.optional(v.number()), stopRequestId: v.optional(v.string()), minutes: v.optional(v.number()) })
    .index('by_work_order', ['workOrderId']).index('by_account_created', ['accountId', 'createdAt']).index('by_technician_start', ['technicianAccountId', 'startedAt']).index('by_account_technician_start', ['accountId', 'technicianAccountId', 'startedAt']).index('by_account_request', ['accountId', 'requestId']).index('by_account_stop_request', ['accountId', 'stopRequestId']),
  automotivePartAllocations: defineTable({ ...versioned, workOrderId: v.id('automotiveWorkOrders'), technicianAccountId: v.id('accounts'), variantId: v.id('hasibVariants'), qty: v.number(), status: v.string(), issueMoveId: v.optional(v.id('hasibStockMoves')), returnMoveId: v.optional(v.id('hasibStockMoves')) })
    .index('by_work_order', ['workOrderId']).index('by_account_request', ['accountId', 'requestId']).index('by_account_technician_created', ['accountId', 'technicianAccountId', 'createdAt']),
  automotiveQualityChecks: defineTable({ accountId: v.id('accounts'), requestId: v.string(), workOrderId: v.id('automotiveWorkOrders'), checklist: v.array(v.object({ text: v.string(), done: v.boolean() })), checkedBy: v.id('accounts'), checkedAt: v.number() })
    .index('by_work_order', ['workOrderId']).index('by_account_request', ['accountId', 'requestId']),
  automotiveExperience: defineTable({ accountId: v.id('accounts'), requestId: v.string(), workOrderId: v.id('automotiveWorkOrders'), rating: v.number(), reason: v.optional(v.string()), submittedAt: v.number() })
    .index('by_account_submitted', ['accountId', 'submittedAt']).index('by_work_order', ['workOrderId']).index('by_account_request', ['accountId', 'requestId']),
  automotiveTasks: defineTable({ accountId: v.id('accounts'), kind: v.string(), entityType: v.string(), entityId: v.string(), status: v.string(), reason: v.string(), assignedAccountId: v.optional(v.id('accounts')), dueAt: v.optional(v.number()), createdAt: v.number(), updatedAt: v.number() })
    .index('by_account_status', ['accountId', 'status']).index('by_account_status_due', ['accountId', 'status', 'dueAt']).index('by_entity', ['entityType', 'entityId']),
};
